include(cdpm_config)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(malformed_manifest tmp)
file(WRITE "${tmp}/packages/demo/package.json" "not-json")
file(WRITE "${tmp}/packages.json" [[{"repo_schema":2,"packages":{"demo":"packages/demo/package.json"}}]])
cdpm_validate_registry("${tmp}/packages.json" valid diagnostics)
assert_false("${valid}" "a malformed manifest fails validation")
assert_match("${diagnostics}" "package 'demo'.*not a JSON object" "the expected manifest diagnostic is emitted")
