include(cdpm_config)

if(NOT UNIX)
    message(STATUS "SKIP: POSIX FIFO unavailable")
    return()
endif()
find_program(mkfifo_program NAMES mkfifo NO_CACHE)
if(NOT mkfifo_program)
    message(STATUS "SKIP: POSIX FIFO unavailable")
    return()
endif()
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/patch_fifo")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}/patches")
execute_process(COMMAND "${mkfifo_program}" "${tmp}/patches/fix.diff" RESULT_VARIABLE fifo_result)
if(NOT fifo_result EQUAL 0)
    message(STATUS "SKIP: POSIX FIFO unavailable")
    return()
endif()
file(WRITE "${tmp}/package.json" [[{"source":{"type":"git","url":"https://example.test/demo.git"},
"versions":{"1":{"rev":"0123456789abcdef0123456789abcdef01234567","patches":["patches/fix.diff"]}}}]])
file(WRITE "${tmp}/packages.json" [[{"version":1,"packages":{"demo":"package.json"}}]])
cdpm_load_repo("${tmp}/packages.json")
cdpm_find_in_repo(demo found meta)
