include(cdpm_config)
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(manifest_symlink_escape tmp)
set(outside "${tmp}-outside")
file(REMOVE_RECURSE "${outside}")
file(MAKE_DIRECTORY "${outside}")
write_registry_manifest("${outside}/package.json")
file(CREATE_LINK "${outside}/package.json" "${tmp}/packages/demo/linked.json" SYMBOLIC RESULT link_result)
if(NOT link_result STREQUAL "0")
    message(STATUS "SKIP: symlink creation unsupported: ${link_result}")
    return()
endif()
file(WRITE "${tmp}/packages.json" [[{"version":1,"packages":{"demo":"packages/demo/linked.json"}}]])
cdpm_load_repo("${tmp}/packages.json")
cdpm_find_in_repo(demo found meta)
