include(cdpm_config)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(malformed_index tmp)
file(WRITE "${tmp}/packages.json" [[{"version":1,"unexpected":true}]])
cdpm_validate_registry("${tmp}/packages.json" valid diagnostics)
assert_false("${valid}" "a malformed index fails validation")
assert_match("${diagnostics}" "unexpected root member 'unexpected'" "the expected index diagnostic is emitted")
