include(cdpm_config)
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(manifest_absolute tmp)
file(WRITE "${tmp}/packages.json" "{\"repo_schema\":2,\"packages\":{\"demo\":\"${tmp}/packages/demo/package.json\"}}")
cdpm_load_repo("${tmp}/packages.json")
