include(cdpm_config)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(malformed_index tmp)
file(WRITE "${tmp}/packages.json" [[{"repo_schema":2,"packages":[]}]])
cdpm_validate_registry("${tmp}/packages.json" valid diagnostics)
assert_false("${valid}" "a malformed index fails validation")
assert_match("${diagnostics}" "'packages' must be an object map" "the expected index diagnostic is emitted")
