cmake_policy(SET CMP0053 NEW)

include(cdpm_config)
include(cdpm_hash)
include(cdpm_lockfile)
include(cdpm_cps)
include("${CDPM_TEST_HELPERS}/helpers.cmake")

set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/schema_equivalence")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}/patches")
file(WRITE "${tmp}/patches/fix.diff" "equivalent patch")
set(package [[{"find_package_name":"PublicDemo","source":{"type":"git","url":"https://example.test/demo.git"},
"default_version":"1.0.0","versions":{"1.0.0":{"rev":"0123456789abcdef0123456789abcdef01234567",
"patches":["patches/fix.diff"]}},"components":{"demo":{"type":"interface"}}}]])
file(WRITE "${tmp}/schema1.json" "{\"repo_schema\":1,\"packages\":{\"demo\":${package}}}")
file(WRITE "${tmp}/package.json" "${package}")
file(WRITE "${tmp}/schema2.json" [[{"repo_schema":2,"packages":{"demo":"package.json"}}]])
set(CDPM_PROJECT_DIR "${tmp}")

function(capture_schema registry capture_name)
    _cdpm_registry_reset()
    cdpm_load_repo("${registry}")
    cdpm_find_package_in_repo(PublicDemo found package_key meta)
    assert_true("${found}" "schema alias lookup succeeds")
    assert_eq("${package_key}" demo "schema alias lookup is canonical")
    cdpm_compute_config_hash("${package_key}" 1.0.0 "${meta}" hash)
    cdpm_get_package_source("${package_key}" "${meta}" 1.0.0 source dev)
    _cdpm_lockfile_compose_entry(1.0.0 "${hash}" "${source}" "${dev}" lock_entry)
    _cdpm_cps_compose("${package_key}" 1.0.0 "${tmp}/store/demo/${hash}" "${meta}" cps)
    set(${capture_name}_meta "${meta}" PARENT_SCOPE)
    set(${capture_name}_hash "${hash}" PARENT_SCOPE)
    set(${capture_name}_lock "${lock_entry}" PARENT_SCOPE)
    set(${capture_name}_cps "${cps}" PARENT_SCOPE)
endfunction()

capture_schema("${tmp}/schema1.json" schema1)
capture_schema("${tmp}/schema2.json" schema2)
assert_json_eq("${schema2_meta}" "${schema1_meta}" "schema versions materialize equivalent metadata")
assert_eq("${schema2_hash}" "${schema1_hash}" "schema versions produce equivalent config hashes")
assert_json_eq("${schema2_lock}" "${schema1_lock}" "schema versions produce equivalent lock entries")
assert_json_eq("${schema2_cps}" "${schema1_cps}" "schema versions produce equivalent CPS metadata")

file(REMOVE_RECURSE "${tmp}")
message(STATUS "PASS: schema 1 and schema 2 preserve hash, lock, and CPS semantics")
