include(cdpm_config)
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(malformed_value tmp)
file(WRITE "${tmp}/packages.json" [[{"version":2,"packages":{"demo":42}}]])
cdpm_load_repo("${tmp}/packages.json")
