include(cdpm_config)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(digit_first tmp)
file(MAKE_DIRECTORY "${tmp}/packages/7")
file(RENAME "${tmp}/packages/d/demo" "${tmp}/packages/7/7zip")
file(WRITE "${tmp}/packages.json" [[{"version":1}]])
cdpm_load_repo("${tmp}/packages.json")
cdpm_find_in_repo(7zip found meta)
assert_true("${found}" "digit-first package is discovered")
