include(cdpm_config)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")

set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/masks_overlay")
file(REMOVE_RECURSE "${tmp}")
foreach(repo IN ITEMS first second)
    file(MAKE_DIRECTORY "${tmp}/${repo}/demo" "${tmp}/${repo}/extra")
endforeach()
file(WRITE "${tmp}/first/demo/package.json" "{\"source\":{\"type\":\"git\",\"url\":\"https://first.test/demo.git\"},\"versions\":{\"1\":{\"rev\":\"0123456789abcdef0123456789abcdef01234567\"}}}")
file(WRITE "${tmp}/first/extra/package.json" "{\"source\":{\"type\":\"git\",\"url\":\"https://first.test/extra.git\"},\"versions\":{\"1\":{\"rev\":\"0123456789abcdef0123456789abcdef01234567\"}}}")
file(WRITE "${tmp}/second/demo/package.json" "{\"source\":{\"type\":\"git\",\"url\":\"https://second.test/demo.git\"},\"versions\":{\"2\":{\"rev\":\"0123456789abcdef0123456789abcdef01234567\"}}}")
file(WRITE "${tmp}/second/extra/package.json" "{\"source\":{\"type\":\"git\",\"url\":\"https://second.test/extra.git\"},\"versions\":{\"2\":{\"rev\":\"0123456789abcdef0123456789abcdef01234567\"}}}")
foreach(repo IN ITEMS first second)
    file(WRITE "${tmp}/${repo}/packages.json" "{\"version\":1,\"packages\":{\"demo\":\"demo/package.json\",\"extra\":\"extra/package.json\"}}")
endforeach()

set_property(GLOBAL PROPERTY CDPM_MERGED_REPO "")
set_property(GLOBAL PROPERTY CDPM_REPO_PROVENANCE "")
cdpm_load_repo("${tmp}/first/packages.json" PACKAGES [=[["demo"]]=])
cdpm_load_repo("${tmp}/second/packages.json" PACKAGES [=[["*"]]=])
cdpm_find_in_repo(demo demo_found demo_meta)
cdpm_find_in_repo(extra extra_found extra_meta)
assert_true("${demo_found}" "masked first manifest-index package is loaded")
assert_true("${extra_found}" "later manifest-index repo supplies package masked out of the first")
string(JSON demo_url GET "${demo_meta}" source url)
string(JSON extra_url GET "${extra_meta}" source url)
assert_eq("${demo_url}" "https://first.test/demo.git" "first registration wins across manifest-index repos")
assert_eq("${extra_url}" "https://second.test/extra.git" "manifest-index masks apply before registration")
_cdpm_registry_get_provenance(demo unused demo_provenance)
string(JSON demo_root GET "${demo_provenance}" repo_root)
assert_eq("${demo_root}" "${tmp}/first" "first-winning package retains first-repo provenance")

file(REMOVE_RECURSE "${tmp}")
message(STATUS "PASS: version 1 masks and first-registration-wins overlay are preserved")
