include(cdpm_config)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(ignored_packages tmp)
file(WRITE "${tmp}/packages.json" [[{"version":1,"packages":{"demo":"../outside.json"}}]])
cdpm_validate_registry("${tmp}/packages.json" valid diagnostics)
assert_true("${valid}" "the legacy packages map is ignored")
file(WRITE "${tmp}/packages.json" [[{"version":1,"packages":["garbage",42]}]])
cdpm_validate_registry("${tmp}" valid diagnostics)
assert_true("${valid}" "packages member of any type is ignored")
file(WRITE "${tmp}/packages.json" [[{"version":1}]])
cdpm_validate_registry("${tmp}" valid diagnostics)
assert_true("${valid}" "packages member is optional")
