include(cdpm_config)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fixture_helpers.cmake")
init_registry_fixture(directory_symlink_escape tmp)
set(outside "${tmp}-outside")
file(MAKE_DIRECTORY "${outside}")
write_registry_manifest("${outside}/package.json")
file(REMOVE_RECURSE "${tmp}/packages/d/demo")
file(CREATE_LINK "${outside}" "${tmp}/packages/d/demo" SYMBOLIC RESULT link_result)
if(NOT link_result STREQUAL "0")
    message("SKIP: symlink creation unsupported: ${link_result}")
    return()
endif()
file(WRITE "${tmp}/packages.json" [[{"version":1}]])
cdpm_validate_registry("${tmp}/packages.json" valid diagnostics)
assert_false("${valid}" "symlinked package directory outside registry is rejected")
assert_match("${diagnostics}" "escapes repository root" "containment diagnostic identifies the escape")
