cmake_policy(SET CMP0011 NEW)
include(cdpm_resolve)
include("${CDPM_TEST_HELPERS}/helpers.cmake")

set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/shared")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}")
set(CDPM_PROJECT_DIR "${tmp}")
set(CDPM_STORE_DIR "${tmp}/store")
set(CDPM_RUNTIME_DIR "${tmp}/runtime")
set_property(GLOBAL PROPERTY CDPM_CONFIG_LOADED TRUE)
set_property(GLOBAL PROPERTY CDPM_EFFECTIVE_CONFIG [[{"packages":{},"options":{},"user":{}}]])
set_property(GLOBAL PROPERTY CDPM_REPO_JSON [[{"repos":[]}]])
set(repo [[{"packages":{
    "leaf":{"find_package_name":"ManagedLeaf","source":{"type":"local","url":"."},"default_version":"1","versions":{"1":{}}},
    "left":{"source":{"type":"local","url":"."},"default_version":"1","versions":{"1":{}},"dependencies":{"ManagedLeaf":{"version":"1"}}},
    "right":{"source":{"type":"local","url":"."},"default_version":"1","versions":{"1":{}},"dependencies":{"leaf":{"version":"1"}}},
    "parent":{"source":{"type":"local","url":"."},"default_version":"1","versions":{"1":{}},"dependencies":{"left":{},"right":{}}}
}}]])
set_property(GLOBAL PROPERTY CDPM_MERGED_REPO "${repo}")

function(cdpm_build_dependency pkg version hash meta)
    get_property(order GLOBAL PROPERTY test_build_order)
    list(APPEND order "${pkg}")
    set_property(GLOBAL PROPERTY test_build_order "${order}")
    file(MAKE_DIRECTORY "${CDPM_STORE_DIR}/${pkg}/${hash}")
    file(TOUCH "${CDPM_STORE_DIR}/${pkg}/${hash}/.cdpm_installed")
endfunction()

cdpm_resolve_and_build(parent "" context)
get_property(order GLOBAL PROPERTY test_build_order)
assert_eq("${order}" "leaf;left;right;parent" "shared leaf is built once in dependency-first order")
string(JSON managed_count LENGTH "${context}" managed)
assert_eq("${managed_count}" 4 "context records the full graph")
file(READ "${tmp}/cdpm.lock.json" lock)
string(JSON package_count LENGTH "${lock}" packages)
assert_eq("${package_count}" 4 "lock records the full graph")
string(JSON local_dev GET "${lock}" packages leaf dev)
assert_true("${local_dev}" "normal local sources are locked as non-reproducible dev entries")
string(JSON parent_dependencies GET "${lock}" packages parent dependencies)
string(JSON parent_dependency_count LENGTH "${parent_dependencies}")
assert_eq("${parent_dependency_count}" 2 "parent lock records direct identities")
string(JSON left_alias_identity GET "${lock}" packages left dependencies leaf)
assert_json_member("${left_alias_identity}" package leaf "public alias is canonicalized to the registry key")
get_property(resolver_records GLOBAL PROPERTY __CDPM_RESOLVER_RECORDS)
assert_eq("${resolver_records}" "" "resolver state is cleaned after success")
get_property(staged_entries GLOBAL PROPERTY __CDPM_RESOLVER_STAGED_ENTRIES)
assert_eq("${staged_entries}" "" "staged lock entries are cleaned after success")
file(REMOVE_RECURSE "${tmp}")
message(STATUS "PASS: resolve.shared_graph")
