cmake_policy(SET CMP0140 NEW)
include("${CDPM_TEST_HELPERS}/helpers.cmake")

cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH module_dir)
cmake_path(GET module_dir PARENT_PATH unit_dir)
cmake_path(GET unit_dir PARENT_PATH tests_dir)
set(cdpm_root "${tests_dir}")
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/structural-validation")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}")
set(runner "${tmp}/read.cmake")
file(WRITE "${runner}" "list(PREPEND CMAKE_MODULE_PATH \"${cdpm_root}/core\")\n"
    "include(cdpm_lockfile)\ncdpm_read_lockfile(PATH \"\${LOCK}\")\n")

function(expect_invalid name json)
    set(path "${tmp}/${name}.json")
    file(WRITE "${path}" "${json}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DLOCK=${path}" -P "${runner}"
        RESULT_VARIABLE rc OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(rc EQUAL 0)
        message(FATAL_ERROR "FAIL: malformed lock '${name}' was accepted")
    endif()
endfunction()

expect_invalid(top [=[[]]=])
expect_invalid(schema [[{"lock_schema":2,"packages":{},"repos":[]}]])
expect_invalid(packages [[{"lock_schema":1,"packages":[],"repos":[]}]])
expect_invalid(entry [[{"lock_schema":1,"packages":{"x":1},"repos":[]}]])
expect_invalid(version [[{"lock_schema":1,"packages":{"x":{"config_hash":"h","dependencies":{},"dev":false}},"repos":[]}]])
expect_invalid(dependencies [[{"lock_schema":1,"packages":{"x":{"version":"1","config_hash":"h","dependencies":[],"dev":false}},"repos":[]}]])
expect_invalid(dev [[{"lock_schema":1,"packages":{"x":{"version":"1","config_hash":"h","dependencies":{},"dev":"false"}},"repos":[]}]])
expect_invalid(system [[{"lock_schema":1,"packages":{"x":{"version":"1","config_hash":"h","dependencies":{},"system_dependencies":[],"dev":false}},"repos":[]}]])
expect_invalid(identity [[{"lock_schema":1,"packages":{"x":{"version":"1","config_hash":"h","dependencies":{"y":{"package":"y","version":"1"}},"dev":false}},"repos":[]}]])
expect_invalid(repos [[{"lock_schema":1,"packages":{},"repos":[{"url":"repo","baseline":"abc"}]}]])

set(missing "${tmp}/missing.json")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DLOCK=${missing}" -P "${runner}" RESULT_VARIABLE missing_rc)
assert_eq("${missing_rc}" 0 "missing lockfile produces a valid skeleton")
file(REMOVE_RECURSE "${tmp}")
message(STATUS "PASS: read.structural_validation")
