include("${CDPM_TEST_HELPERS}/helpers.cmake")
cmake_policy(SET CMP0140 NEW)

cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH tests_dir)
cmake_path(GET tests_dir PARENT_PATH cdpm_root)
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/resolver_lock_modes")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}")
set(runner "${tmp}/runner.cmake")
file(WRITE "${runner}" [=[
cmake_policy(SET CMP0011 NEW)
cmake_policy(SET CMP0140 NEW)
list(PREPEND CMAKE_MODULE_PATH "@CORE@")
include(cdpm_cli_commands)
set(CDPM_PROJECT_DIR "${PROJECT_DIR}")
set(CDPM_STORE_DIR "${PROJECT_DIR}/store")
set(CDPM_RUNTIME_DIR "${PROJECT_DIR}/runtime")
set_property(GLOBAL PROPERTY CDPM_CONFIG_LOADED TRUE)
set_property(GLOBAL PROPERTY CDPM_EFFECTIVE_CONFIG [[{"packages":{},"options":{},"user":{}}]])
set_property(GLOBAL PROPERTY CDPM_REPO_JSON
    "{\"repos\":[{\"kind\":\"git\",\"url\":\"registry-url\",\"baseline\":\"${REPO_PIN}\"}]}")
set(repo [==[{"packages":{
    "child":{"source":{"type":"git","url":"local-child"},"default_version":"1",
        "versions":{"1":{"rev":"child-pin"}}},
    "root":{"source":{"type":"git","url":"local-root"},"default_version":"1",
        "dependencies":{"child":{}},
        "system_dependencies":{"Fake":{"mode":"CONFIG","identity_targets":["Fake::Fake"]}},
        "versions":{"1":{"rev":"@ROOT_REV@"}}},
    "later":{"source":{"type":"git","url":"local-later"},"default_version":"1",
        "versions":{"1":{"rev":"@LATER_REV@"}}}
}}]==])
string(JSON repo SET "${repo}" packages root versions 1 rev "\"${ROOT_REV}\"")
string(JSON repo SET "${repo}" packages later versions 1 rev "\"${LATER_REV}\"")
set_property(GLOBAL PROPERTY CDPM_MERGED_REPO "${repo}")
function(cdpm_load_repos)
    file(APPEND "${REPO_LOAD_MARKER}" "loaded\n")
endfunction()
function(cdpm_probe_system_dependencies pkg declarations out)
    set(${out} "{\"Fake\":{\"identity\":\"${SYSTEM_ID}\"}}")
    return(PROPAGATE ${out})
endfunction()
function(cdpm_build_dependency pkg version hash meta)
    file(APPEND "${BUILD_MARKER}" "${pkg}\n")
    if(pkg STREQUAL FAIL_PACKAGE)
        message(FATAL_ERROR "intentional build failure for ${pkg}")
    endif()
    file(MAKE_DIRECTORY "${CDPM_STORE_DIR}/${pkg}/${hash}")
    file(TOUCH "${CDPM_STORE_DIR}/${pkg}/${hash}/.cdpm_installed")
endfunction()
cdpm_read_lockfile(PATH "${LOCK_PATH}")
if(ACTION STREQUAL "INIT")
    cdpm_resolve_and_build(root 1 context LOCK_MODE UPDATE)
    cdpm_resolve_and_build(later 1 context LOCK_MODE UPDATE)
elseif(ACTION STREQUAL "PROVISION")
    get_property(__lock_json GLOBAL PROPERTY CDPM_LOCKFILE_JSON)
    _cdpm_lockfile_get_roots("${__lock_json}" __roots)
    foreach(__root IN LISTS __roots)
        string(JSON __ver GET "${__lock_json}" packages "${__root}" version)
        cdpm_resolve_and_build("${__root}" "${__ver}" context LOCK_MODE VERIFY VALIDATE_ONLY)
    endforeach()
    foreach(__root IN LISTS __roots)
        string(JSON __ver GET "${__lock_json}" packages "${__root}" version)
        cdpm_resolve_and_build("${__root}" "${__ver}" context LOCK_MODE VERIFY)
    endforeach()
else()
    cdpm_resolve_and_build(root 1 context LOCK_MODE "${LOCK_MODE}")
endif()
]=])
file(READ "${runner}" runner_content)
string(REPLACE "@CORE@" "${cdpm_root}/core" runner_content "${runner_content}")
file(WRITE "${runner}" "${runner_content}")

function(run_case name expect_success)
    set(marker "${tmp}/${name}.builds")
    set(repo_load_marker "${tmp}/${name}.repos")
    file(REMOVE "${marker}")
    file(REMOVE "${repo_load_marker}")
    execute_process(COMMAND "${CMAKE_COMMAND}"
        "-DPROJECT_DIR=${tmp}" "-DLOCK_PATH=${ARG_LOCK}" "-DLOCK_MODE=${ARG_MODE}"
        "-DROOT_REV=${ARG_REV}" "-DSYSTEM_ID=${ARG_SYSTEM}" "-DBUILD_MARKER=${marker}"
        "-DLATER_REV=${ARG_LATER_REV}" "-DREPO_PIN=${ARG_REPO_PIN}" "-DACTION=${ARG_ACTION}"
        "-DREPO_LOAD_MARKER=${repo_load_marker}" "-DFAIL_PACKAGE=${ARG_FAIL}" -P "${runner}"
        RESULT_VARIABLE rc OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expect_success AND NOT rc EQUAL 0)
        message(FATAL_ERROR "FAIL: ${name} unexpectedly failed\n${output}${error}")
    elseif(NOT expect_success AND rc EQUAL 0)
        message(FATAL_ERROR "FAIL: ${name} unexpectedly succeeded")
    endif()
    set(${name}_marker "${marker}" PARENT_SCOPE)
    set(${name}_repo_marker "${repo_load_marker}" PARENT_SCOPE)
    set(${name}_output "${output}${error}" PARENT_SCOPE)
endfunction()

set(lock "${tmp}/strict.lock.json")
set(ARG_LOCK "${lock}")
set(ARG_MODE UPDATE)
set(ARG_REV root-pin)
set(ARG_SYSTEM system-one)
set(ARG_FAIL "")
set(ARG_LATER_REV later-pin)
set(ARG_REPO_PIN aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
set(ARG_ACTION INIT)
run_case(initial TRUE)
file(SHA256 "${lock}" baseline_sha)

set(ARG_MODE VERIFY)
set(ARG_ACTION RESOLVE)
run_case(success TRUE)
file(SHA256 "${lock}" success_sha)
assert_eq("${success_sha}" "${baseline_sha}" "successful VERIFY leaves lock byte-identical")

foreach(drift IN ITEMS source system_artifact system_definition)
    set(ARG_REV root-pin)
    set(ARG_SYSTEM system-one)
    if(drift STREQUAL source)
        set(ARG_REV changed-pin)
    elseif(drift STREQUAL system_artifact)
        set(ARG_SYSTEM artifact-two)
    else()
        set(ARG_SYSTEM definition-two)
    endif()
    run_case("${drift}_drift" FALSE)
    if(EXISTS "${${drift}_drift_marker}")
        message(FATAL_ERROR "FAIL: ${drift} drift reached the build")
    endif()
    file(SHA256 "${lock}" drift_sha)
    assert_eq("${drift_sha}" "${baseline_sha}" "${drift} drift leaves lock byte-identical")
endforeach()

set(ARG_REV root-pin)
set(ARG_SYSTEM system-one)
file(REMOVE_RECURSE "${tmp}/store")
set(ARG_REPO_PIN bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb)
run_case(repo_drift FALSE)
if(EXISTS "${repo_drift_marker}")
    message(FATAL_ERROR "FAIL: repository pin drift reached the build")
endif()
if(EXISTS "${repo_drift_repo_marker}")
    message(FATAL_ERROR "FAIL: repository pin drift reached repository materialization")
endif()
file(SHA256 "${lock}" repo_drift_sha)
assert_eq("${repo_drift_sha}" "${baseline_sha}" "repository pin drift leaves lock byte-identical")
if(EXISTS "${tmp}/store")
    message(FATAL_ERROR "FAIL: repository pin drift mutated the store before comparison")
endif()
set(ARG_REPO_PIN aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)

file(READ "${lock}" dev_lock)
string(JSON dev_lock SET "${dev_lock}" packages root dev true)
set(dev_lock_path "${tmp}/dev.lock.json")
file(WRITE "${dev_lock_path}" "${dev_lock}\n")
file(SHA256 "${dev_lock_path}" dev_before)
set(ARG_LOCK "${dev_lock_path}")
set(ARG_REV root-pin)
set(ARG_SYSTEM system-one)
run_case(dev_rejected FALSE)
assert_match("${dev_rejected_output}" "dev:true" "VERIFY rejects dev entries")
if(EXISTS "${dev_rejected_marker}")
    message(FATAL_ERROR "FAIL: dev lock reached the build")
endif()
file(SHA256 "${dev_lock_path}" dev_after)
assert_eq("${dev_after}" "${dev_before}" "dev rejection leaves lock byte-identical")

set(ARG_LOCK "${lock}")
set(ARG_MODE UPDATE)
set(ARG_REV changed-pin)
set(ARG_SYSTEM system-two)
set(ARG_FAIL root)
run_case(partial_failure FALSE)
file(READ "${partial_failure_marker}" partial_builds)
assert_match("${partial_builds}" "child.*root" "partial graph failure occurs after the child build")
file(SHA256 "${lock}" partial_sha)
assert_eq("${partial_sha}" "${baseline_sha}" "partial graph failure does not commit staged entries")

# Provision validates every lock root before starting its build pass. A drift in the later root therefore
# leaves even the earlier roots untouched when the store is empty.
file(REMOVE_RECURSE "${tmp}/store")
set(ARG_MODE VERIFY)
set(ARG_ACTION PROVISION)
set(ARG_FAIL "")
set(ARG_REV root-pin)
set(ARG_LATER_REV changed-later-pin)
set(ARG_SYSTEM system-one)
run_case(later_root_drift FALSE)
if(EXISTS "${later_root_drift_marker}")
    message(FATAL_ERROR "FAIL: whole-lock preflight allowed a build before later-root drift was detected")
endif()
file(SHA256 "${lock}" later_drift_sha)
assert_eq("${later_drift_sha}" "${baseline_sha}" "later-root drift leaves lock byte-identical")

set(ARG_LATER_REV later-pin)
run_case(provision_success TRUE)
file(STRINGS "${provision_success_marker}" provision_builds)
list(SORT provision_builds)
assert_eq("${provision_builds}" "child;later;root" "provision builds each graph node exactly once from roots")
file(SHA256 "${lock}" provision_success_sha)
assert_eq("${provision_success_sha}" "${baseline_sha}" "successful provision leaves lock byte-identical")

file(READ "${lock}" malformed_lock)
string(JSON malformed_lock REMOVE "${malformed_lock}" packages later version)
set(malformed_path "${tmp}/malformed.lock.json")
file(WRITE "${malformed_path}" "${malformed_lock}\n")
file(SHA256 "${malformed_path}" malformed_before)
set(ARG_LOCK "${malformed_path}")
run_case(malformed_preflight FALSE)
if(EXISTS "${malformed_preflight_marker}")
    message(FATAL_ERROR "FAIL: malformed lock reached the build")
endif()
file(SHA256 "${malformed_path}" malformed_after)
assert_eq("${malformed_after}" "${malformed_before}" "malformed preflight leaves lock byte-identical")

file(READ "${lock}" dangling_lock)
string(JSON dangling_lock SET "${dangling_lock}" packages root dependencies child package [["missing"]])
set(dangling_path "${tmp}/dangling.lock.json")
file(WRITE "${dangling_path}" "${dangling_lock}\n")
set(ARG_LOCK "${dangling_path}")
run_case(dangling_reference FALSE)
assert_match("${dangling_reference_output}" "references missing package" "dangling lock child is fatal")
if(EXISTS "${dangling_reference_marker}")
    message(FATAL_ERROR "FAIL: dangling lock reached the build")
endif()

set(cycle_entry_a [[{"version":"1","config_hash":"a","dependencies":{"b":{"package":"b","version":"1","config_hash":"b"}},"dev":false}]])
set(cycle_entry_b [[{"version":"1","config_hash":"b","dependencies":{"a":{"package":"a","version":"1","config_hash":"a"}},"dev":false}]])
set(rootless [[{"lock_schema":1,"packages":{},"host_packages":{},"repos":[]}]])
string(JSON rootless SET "${rootless}" packages a "${cycle_entry_a}")
string(JSON rootless SET "${rootless}" packages b "${cycle_entry_b}")
set(rootless_path "${tmp}/rootless.lock.json")
file(WRITE "${rootless_path}" "${rootless}\n")
set(ARG_LOCK "${rootless_path}")
run_case(rootless_graph FALSE)
assert_match("${rootless_graph_output}" "has no roots" "rootless lock graph is fatal")
if(EXISTS "${rootless_graph_marker}")
    message(FATAL_ERROR "FAIL: rootless lock reached the build")
endif()

file(REMOVE_RECURSE "${tmp}")
message(STATUS "PASS: resolver lock UPDATE is atomic and VERIFY is strict/read-only")
