# cdpm_registry_converter.cmake - Controlled schema-1 to schema-2 registry conversion.

include_guard(GLOBAL)

cmake_policy(SET CMP0140 NEW)

include(cdpm_config)

function(_cdpm_converter_asset package_key authored project_dir package_dir copied_names copied_sources
        out_authored out_names out_sources)
    _cdpm_registry_validate_relative_path("${authored}" "schema-1 package '${package_key}' patch conversion")
    _cdpm_registry_resolve_contained_file("${project_dir}" "${authored}"
        "schema-1 package '${package_key}' patch conversion" source_path)

    set(normalized "${authored}")
    cmake_path(NORMAL_PATH normalized OUTPUT_VARIABLE normalized)
    cmake_path(GET normalized FILENAME filename)
    if(filename STREQUAL "" OR filename MATCHES [[^[.]([.]?)$]])
        message(FATAL_ERROR "[cdpm] schema-1 package '${package_key}': unsafe patch filename '${authored}'.")
    endif()
    set(manifest_path "patches/${filename}")

    set(names "${copied_names}")
    set(sources "${copied_sources}")
    list(FIND names "${manifest_path}" existing_index)
    if(existing_index GREATER_EQUAL 0)
        list(GET sources ${existing_index} existing_source)
        if(NOT existing_source STREQUAL source_path)
            message(FATAL_ERROR "[cdpm] schema-1 package '${package_key}': patch paths resolve to different files "
                "with the ambiguous destination name '${manifest_path}'.")
        endif()
    else()
        file(MAKE_DIRECTORY "${package_dir}/patches")
        file(COPY_FILE "${source_path}" "${package_dir}/${manifest_path}" ONLY_IF_DIFFERENT)
        list(APPEND names "${manifest_path}")
        list(APPEND sources "${source_path}")
    endif()

    set(${out_authored} "${manifest_path}")
    set(${out_names} "${names}")
    set(${out_sources} "${sources}")
    return(PROPAGATE ${out_authored} ${out_names} ${out_sources})
endfunction()

function(_cdpm_converter_rewrite_patches package_key metadata project_dir package_dir out_metadata)
    set(result "${metadata}")
    set(copied_names "")
    set(copied_sources "")

    string(JSON patches ERROR_VARIABLE patches_err GET "${result}" patches)
    if(NOT patches_err)
        string(JSON patch_count LENGTH "${patches}")
        if(patch_count GREATER 0)
            math(EXPR patch_last "${patch_count} - 1")
            foreach(i RANGE 0 ${patch_last})
                string(JSON authored GET "${patches}" ${i} file)
                _cdpm_converter_asset("${package_key}" "${authored}" "${project_dir}" "${package_dir}"
                    "${copied_names}" "${copied_sources}" rewritten copied_names copied_sources)
                string(JSON entry GET "${patches}" ${i})
                _cdpm_json_set_safe("${entry}" file "${rewritten}" STRING entry)
                string(JSON patches SET "${patches}" ${i} "${entry}")
            endforeach()
            string(JSON result SET "${result}" patches "${patches}")
        endif()
    endif()

    string(JSON versions ERROR_VARIABLE versions_err GET "${result}" versions)
    if(NOT versions_err)
        _cdpm_json_foreach("${versions}" version_keys)
        foreach(version IN LISTS version_keys)
            string(JSON version_patches ERROR_VARIABLE version_patches_err GET
                "${versions}" "${version}" patches)
            if(version_patches_err)
                continue()
            endif()
            string(JSON patch_count LENGTH "${version_patches}")
            if(patch_count GREATER 0)
                math(EXPR patch_last "${patch_count} - 1")
                foreach(i RANGE 0 ${patch_last})
                    string(JSON authored GET "${version_patches}" ${i})
                    _cdpm_converter_asset("${package_key}" "${authored}" "${project_dir}" "${package_dir}"
                        "${copied_names}" "${copied_sources}" rewritten copied_names copied_sources)
                    _cdpm_json_set_safe("${version_patches}" ${i} "${rewritten}" STRING version_patches)
                endforeach()
            endif()
            string(JSON versions SET "${versions}" "${version}" patches "${version_patches}")
        endforeach()
        string(JSON result SET "${result}" versions "${versions}")
    endif()

    cdpm_canonical_json("${result}" result)
    set(${out_metadata} "${result}")
    return(PROPAGATE ${out_metadata})
endfunction()

function(_cdpm_converter_require_replaceable path context)
    if(IS_SYMLINK "${path}" OR (EXISTS "${path}" AND NOT IS_DIRECTORY "${path}"))
        message(FATAL_ERROR "[cdpm] ${context} is not a replaceable converter output directory: '${path}'.")
    endif()
    if(EXISTS "${path}" AND NOT EXISTS "${path}/.cdpm-schema2-converter-output")
        message(FATAL_ERROR "[cdpm] ${context} already exists and is not marked as controlled converter output: "
            "'${path}'.")
    endif()
endfunction()

# Converts a complete physical schema-1 registry into a separately published schema-2 tree. The source is loaded by
# the production loader and package semantic validator. Existing destinations are replaceable only when they carry the
# converter ownership marker; arbitrary directories are never removed.
function(cdpm_convert_registry_schema1_to_schema2)
    cmake_parse_arguments(arg "" "SOURCE;DESTINATION;PROJECT_DIR" "" ${ARGN})
    foreach(required IN ITEMS SOURCE DESTINATION PROJECT_DIR)
        if(NOT DEFINED arg_${required} OR arg_${required} STREQUAL "")
            message(FATAL_ERROR "[cdpm] cdpm_convert_registry_schema1_to_schema2 requires ${required}.")
        endif()
    endforeach()

    foreach(path_var IN ITEMS SOURCE DESTINATION PROJECT_DIR)
        set(path "${arg_${path_var}}")
        if(NOT IS_ABSOLUTE "${path}")
            cmake_path(ABSOLUTE_PATH path NORMALIZE OUTPUT_VARIABLE path)
        else()
            cmake_path(NORMAL_PATH path OUTPUT_VARIABLE path)
        endif()
        set(arg_${path_var} "${path}")
    endforeach()
    if(NOT IS_DIRECTORY "${arg_PROJECT_DIR}")
        message(FATAL_ERROR "[cdpm] converter PROJECT_DIR is not a directory: '${arg_PROJECT_DIR}'.")
    endif()
    if(arg_DESTINATION STREQUAL arg_PROJECT_DIR OR arg_DESTINATION STREQUAL arg_SOURCE)
        message(FATAL_ERROR "[cdpm] converter DESTINATION must be separate from SOURCE and PROJECT_DIR.")
    endif()
    cmake_path(GET arg_DESTINATION PARENT_PATH destination_parent)
    if(NOT IS_DIRECTORY "${destination_parent}")
        message(FATAL_ERROR "[cdpm] converter destination parent does not exist: '${destination_parent}'.")
    endif()

    _cdpm_registry_read_regular_file("${arg_SOURCE}" "schema-1 converter source" "" source_raw source_real)
    string(JSON schema ERROR_VARIABLE schema_err GET "${source_raw}" repo_schema)
    if(schema_err OR NOT schema EQUAL 1)
        message(FATAL_ERROR "[cdpm] converter SOURCE must be a repo_schema 1 registry.")
    endif()

    _cdpm_converter_require_replaceable("${arg_DESTINATION}" "converter DESTINATION")
    set(stage "${arg_DESTINATION}.cdpm-schema2-stage")
    set(backup "${arg_DESTINATION}.cdpm-schema2-backup")
    _cdpm_converter_require_replaceable("${stage}" "converter staging directory")
    _cdpm_converter_require_replaceable("${backup}" "converter backup directory")
    if(EXISTS "${stage}")
        file(REMOVE_RECURSE "${stage}")
    endif()
    file(MAKE_DIRECTORY "${stage}")
    file(WRITE "${stage}/.cdpm-schema2-converter-output" "cdpm schema-2 converter output\n")

    set(CDPM_PROJECT_DIR "${arg_PROJECT_DIR}")
    _cdpm_registry_reset()
    cdpm_load_repo("${source_real}")
    get_property(merged GLOBAL PROPERTY CDPM_MERGED_REPO)
    string(JSON packages GET "${merged}" packages)
    _cdpm_json_foreach("${packages}" package_keys)
    list(SORT package_keys)

    set(index_packages "{}")
    foreach(package_key IN LISTS package_keys)
        if(NOT package_key MATCHES [[^[a-z0-9][a-z0-9_.+-]*$]])
            message(FATAL_ERROR "[cdpm] converter cannot form a safe canonical package directory for "
                "'${package_key}'.")
        endif()
        string(JSON metadata GET "${packages}" "${package_key}")
        string(JSON source_template ERROR_VARIABLE template_err GET "${metadata}" source url_template)
        string(JSON build_script ERROR_VARIABLE script_err GET "${metadata}" build_script)
        if(NOT template_err OR NOT script_err)
            message(FATAL_ERROR "[cdpm] schema-1 package '${package_key}': url_template and build_script conversion "
                "are not supported.")
        endif()

        set(package_dir "${stage}/packages/${package_key}")
        file(MAKE_DIRECTORY "${package_dir}")
        _cdpm_converter_rewrite_patches("${package_key}" "${metadata}" "${arg_PROJECT_DIR}"
            "${package_dir}" manifest)
        file(WRITE "${package_dir}/package.json" "${manifest}\n")
        _cdpm_json_set_safe("${index_packages}" "${package_key}"
            "packages/${package_key}/package.json" STRING index_packages)
    endforeach()

    set(index "{}")
    string(JSON index SET "${index}" repo_schema 2)
    string(JSON index SET "${index}" packages "${index_packages}")
    cdpm_canonical_json("${index}" index)
    file(WRITE "${stage}/packages.json" "${index}\n")

    cdpm_validate_registry("${stage}" valid diagnostics)
    if(NOT valid)
        message(FATAL_ERROR "[cdpm] generated schema-2 registry failed production validation:\n${diagnostics}")
    endif()

    if(EXISTS "${backup}")
        file(REMOVE_RECURSE "${backup}")
    endif()
    if(EXISTS "${arg_DESTINATION}")
        file(RENAME "${arg_DESTINATION}" "${backup}" RESULT rename_old_result)
        if(NOT rename_old_result STREQUAL "0")
            message(FATAL_ERROR "[cdpm] failed to stage existing converter output: ${rename_old_result}")
        endif()
    endif()
    file(RENAME "${stage}" "${arg_DESTINATION}" RESULT publish_result)
    if(NOT publish_result STREQUAL "0")
        if(EXISTS "${backup}")
            file(RENAME "${backup}" "${arg_DESTINATION}")
        endif()
        message(FATAL_ERROR "[cdpm] failed to publish converted registry: ${publish_result}")
    endif()
    if(EXISTS "${backup}")
        file(REMOVE_RECURSE "${backup}")
    endif()
endfunction()
