# cdpm_version.cmake - Shared version loading, comparison, and range handling.

include_guard(GLOBAL)

cmake_policy(VERSION 3.25...4.0)

include(cdpm_basics)

# Test/embedder override hook. The file is not read until ``_cdpm_get_version`` is first called.
if(NOT DEFINED __CDPM_VERSION_FILE OR __CDPM_VERSION_FILE STREQUAL "")
    set(__CDPM_VERSION_FILE "${__CDPM_ROOT}/VERSION")
endif()
set(__CDPM_VERSION_FILE "${__CDPM_VERSION_FILE}" CACHE INTERNAL "cdpm VERSION file path" FORCE)

function(_cdpm_get_version out_var)
    if(NOT DEFINED __CDPM_VERSION_CACHED)
        set(fallback "0.0.0-unknown")
        set(semver_regex [[^[0-9]+\.[0-9]+\.[0-9]+([-+].+)?$]])
        if(EXISTS "${__CDPM_VERSION_FILE}")
            file(READ "${__CDPM_VERSION_FILE}" version)
            string(STRIP "${version}" version)
            if(version STREQUAL "")
                message(WARNING "[cdpm] VERSION file is empty: ${__CDPM_VERSION_FILE} "
                    "-- falling back to '${fallback}'")
                set(version "${fallback}")
            elseif(NOT version MATCHES "${semver_regex}")
                message(WARNING "[cdpm] VERSION file content does not look like semver: "
                    "'${version}' (${__CDPM_VERSION_FILE})")
            endif()
        else()
            message(WARNING "[cdpm] VERSION file not found: ${__CDPM_VERSION_FILE} "
                "-- falling back to '${fallback}'")
            set(version "${fallback}")
        endif()
        set(__CDPM_VERSION_CACHED "${version}" CACHE INTERNAL "cdpm version string (loaded from VERSION file)" FORCE)
    endif()
    set(${out_var} "${__CDPM_VERSION_CACHED}")
    return(PROPAGATE ${out_var})
endfunction()

function(cdpm_parse_version_range spec out_low out_high out_low_incl out_high_incl out_ok)
    set(numeric_version_regex [[^[0-9]+(\.[0-9]+)*$]])
    set(${out_low} "")
    set(${out_high} "")
    set(${out_low_incl} FALSE)
    set(${out_high_incl} FALSE)
    set(${out_ok} FALSE)

    if(spec STREQUAL "*")
        set(${out_low_incl} TRUE)
        set(${out_high_incl} TRUE)
        set(${out_ok} TRUE)
        return(PROPAGATE ${out_low} ${out_high} ${out_low_incl} ${out_high_incl} ${out_ok})
    endif()

    if(spec MATCHES "^([\\[(])(.*)->(.*)([])])$")
        set(open "${CMAKE_MATCH_1}")
        set(low "${CMAKE_MATCH_2}")
        set(high "${CMAKE_MATCH_3}")
        set(close "${CMAKE_MATCH_4}")
        if((NOT low STREQUAL "" AND NOT low MATCHES "${numeric_version_regex}")
                OR (NOT high STREQUAL "" AND NOT high MATCHES "${numeric_version_regex}"))
            return(PROPAGATE ${out_low} ${out_high} ${out_low_incl} ${out_high_incl} ${out_ok})
        endif()
        if(open STREQUAL "[")
            set(low_incl TRUE)
        else()
            set(low_incl FALSE)
        endif()
        if(close STREQUAL "]")
            set(high_incl TRUE)
        else()
            set(high_incl FALSE)
        endif()
        if((low STREQUAL "" AND low_incl) OR (high STREQUAL "" AND high_incl))
            return(PROPAGATE ${out_low} ${out_high} ${out_low_incl} ${out_high_incl} ${out_ok})
        endif()
        set(${out_low} "${low}")
        set(${out_high} "${high}")
        set(${out_low_incl} "${low_incl}")
        set(${out_high_incl} "${high_incl}")
        set(${out_ok} TRUE)
        return(PROPAGATE ${out_low} ${out_high} ${out_low_incl} ${out_high_incl} ${out_ok})
    endif()

    if(spec MATCHES "${numeric_version_regex}")
        set(${out_low} "${spec}")
        set(${out_high} "${spec}")
        set(${out_low_incl} TRUE)
        set(${out_high_incl} TRUE)
        set(${out_ok} TRUE)
    endif()
    return(PROPAGATE ${out_low} ${out_high} ${out_low_incl} ${out_high_incl} ${out_ok})
endfunction()

function(_cdpm_require_exact_version pkg_name context spec out_ver)
    set(${out_ver} "")
    if(spec STREQUAL "")
        return(PROPAGATE ${out_ver})
    endif()
    if(spec MATCHES "[[]|[]]|[()]|[*]|->|[.][.]")
        message(FATAL_ERROR "[cdpm] package '${pkg_name}': version-range request '${spec}' "
            "(${context}) is not supported yet; exact requests/pins only.")
    endif()
    cdpm_parse_version_range("${spec}" low high low_incl high_incl ok)
    if(ok)
        set(${out_ver} "${low}")
    elseif(spec MATCHES "^[0-9]")
        set(${out_ver} "${spec}")
    endif()
    return(PROPAGATE ${out_ver})
endfunction()

function(cdpm_version_in_range version spec out_ok)
    set(${out_ok} FALSE)
    cdpm_parse_version_range("${spec}" low high low_incl high_incl ok)
    if(NOT ok)
        message(FATAL_ERROR "[cdpm] invalid version range '${spec}'.")
    endif()
    if(NOT low STREQUAL "")
        if((low_incl AND version VERSION_LESS "${low}")
                OR (NOT low_incl AND NOT version VERSION_GREATER "${low}"))
            return(PROPAGATE ${out_ok})
        endif()
    endif()
    if(NOT high STREQUAL "")
        if((high_incl AND version VERSION_GREATER "${high}")
                OR (NOT high_incl AND NOT version VERSION_LESS "${high}"))
            return(PROPAGATE ${out_ok})
        endif()
    endif()
    set(${out_ok} TRUE)
    return(PROPAGATE ${out_ok})
endfunction()

# Normalizes an ``applies_to`` JSON value to a JSON array of range strings.
function(_cdpm_normalize_version_ranges ranges_json context out_ranges)
    if(ranges_json STREQUAL "" OR ranges_json STREQUAL "null")
        set(${out_ranges} [=[["*"]]=])
        return(PROPAGATE ${out_ranges})
    endif()
    string(JSON type ERROR_VARIABLE type_err TYPE "${ranges_json}")
    if(type_err OR NOT type MATCHES [[^(STRING|ARRAY|OBJECT)$]])
        message(FATAL_ERROR "[cdpm] ${context} must be a string, array, or object.")
    endif()

    set(result "[]")
    if(type STREQUAL "STRING")
        string(JSON spec GET "${ranges_json}")
        _cdpm_json_set(result "${spec}" TYPE STRING PATH 0)
    elseif(type STREQUAL "ARRAY")
        string(JSON count LENGTH "${ranges_json}")
        if(count GREATER 0)
            math(EXPR last "${count} - 1")
            foreach(i RANGE 0 ${last})
                string(JSON item_type TYPE "${ranges_json}" ${i})
                if(NOT item_type STREQUAL "STRING")
                    message(FATAL_ERROR "[cdpm] ${context}[${i}] must be a version-range string.")
                endif()
                string(JSON spec GET "${ranges_json}" ${i})
                _cdpm_json_set(result "${spec}" TYPE STRING PATH ${i})
            endforeach()
        endif()
    else()
        foreach(bound IN ITEMS from to)
            string(JSON bound_type ERROR_VARIABLE bound_err TYPE "${ranges_json}" "${bound}")
            if(bound_err)
                set(${bound} "")
            elseif(NOT bound_type STREQUAL "STRING")
                message(FATAL_ERROR "[cdpm] ${context}.${bound} must be a version string.")
            else()
                string(JSON ${bound} GET "${ranges_json}" "${bound}")
            endif()
        endforeach()
        foreach(flag IN ITEMS from_include to_include)
            string(JSON flag_type ERROR_VARIABLE flag_err TYPE "${ranges_json}" "${flag}")
            if(flag_err)
                if(flag STREQUAL "from_include")
                    set(${flag} ON)
                else()
                    set(${flag} OFF)
                endif()
            elseif(NOT flag_type STREQUAL "BOOLEAN")
                message(FATAL_ERROR "[cdpm] ${context}.${flag} must be a boolean.")
            else()
                string(JSON ${flag} GET "${ranges_json}" "${flag}")
            endif()
        endforeach()
        if(from STREQUAL "" OR NOT from_include)
            set(open "(")
        else()
            set(open "[")
        endif()
        if(to STREQUAL "" OR NOT to_include)
            set(close ")")
        else()
            set(close "]")
        endif()
        set(spec "${open}${from}->${to}${close}")
        _cdpm_json_set(result "${spec}" TYPE STRING PATH 0)
    endif()
    set(${out_ranges} "${result}")
    return(PROPAGATE ${out_ranges})
endfunction()

function(_cdpm_validate_version_ranges ranges_json context)
    _cdpm_normalize_version_ranges("${ranges_json}" "${context}" ranges)
    string(JSON count LENGTH "${ranges}")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(i RANGE 0 ${last})
            string(JSON spec GET "${ranges}" ${i})
            cdpm_parse_version_range("${spec}" low high low_incl high_incl ok)
            if(NOT ok)
                message(FATAL_ERROR "[cdpm] ${context}: '${spec}' is not a valid version range.")
            endif()
        endforeach()
    endif()
endfunction()

function(cdpm_version_in_ranges version applies_to_json excludes_json out_ok)
    set(${out_ok} FALSE)
    _cdpm_normalize_version_ranges("${applies_to_json}" "applies_to" ranges)
    string(JSON count LENGTH "${ranges}")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(i RANGE 0 ${last})
            string(JSON spec GET "${ranges}" ${i})
            cdpm_version_in_range("${version}" "${spec}" matched)
            if(matched)
                break()
            endif()
        endforeach()
    endif()
    if(NOT matched)
        return(PROPAGATE ${out_ok})
    endif()
    if(NOT excludes_json STREQUAL "" AND NOT excludes_json STREQUAL "null")
        string(JSON count ERROR_VARIABLE excludes_err LENGTH "${excludes_json}")
        if(NOT excludes_err AND count GREATER 0)
            math(EXPR last "${count} - 1")
            foreach(i RANGE 0 ${last})
                string(JSON excluded GET "${excludes_json}" ${i})
                if(version VERSION_EQUAL "${excluded}")
                    return(PROPAGATE ${out_ok})
                endif()
            endforeach()
        endif()
    endif()
    set(${out_ok} TRUE)
    return(PROPAGATE ${out_ok})
endfunction()

function(_cdpm_version_satisfies requested compat_version version out_ok)
    cmake_parse_arguments(arg "EXACT" "" "" ${ARGN})
    set(${out_ok} FALSE)
    if(arg_EXACT AND requested VERSION_EQUAL "${version}")
        set(${out_ok} TRUE)
    elseif(NOT arg_EXACT AND ((compat_version STREQUAL "" AND requested VERSION_EQUAL "${version}")
            OR (NOT compat_version STREQUAL "" AND NOT requested VERSION_LESS "${compat_version}"
                AND NOT requested VERSION_GREATER "${version}")))
        set(${out_ok} TRUE)
    endif()
    return(PROPAGATE ${out_ok})
endfunction()
