# cdpm_orchestrator.cmake - Run hash-sensitive CLI commands inside a real CMake project.
#
# CLI commands that compute configuration hashes (install, provision) are driven through a generated
# orchestrator project so hashes are always produced in a project context with the target toolchain,
# generator and build type. Script-mode hash divergence is eliminated.

include_guard(GLOBAL)

cmake_policy(SET CMP0140 NEW)
cmake_policy(SET CMP0007 NEW)

include(cdpm_config)
include(cdpm_context)
include(cdpm_toolchain)

# Capture the cdpm root at module-include time; functions called later run in a different
# CMAKE_CURRENT_LIST_FILE context (the caller), so they cannot recompute it reliably.
cmake_path(GET CMAKE_CURRENT_LIST_FILE PARENT_PATH __CDPM_ORCHESTRATOR_CORE_DIR)
cmake_path(GET __CDPM_ORCHESTRATOR_CORE_DIR PARENT_PATH __CDPM_ORCHESTRATOR_ROOT)

# .. rst:
# ``_cdpm_orchestrator_env_key(<generator> <build_type> <toolchain_file> <out_key>)``
#
# Computes the orchestrator environment key: the first 16 hex characters of the SHA-256 of
# ``cmake-version|generator|build-type|toolchain-path|toolchain-sha``. An empty toolchain maps to the
# literal token ``none`` so the key stays deterministic.
function(_cdpm_orchestrator_env_key generator build_type toolchain_file out_key)
    if(toolchain_file STREQUAL "")
        set(tc_path "none")
        set(tc_sha "none")
    else()
        cmake_path(ABSOLUTE_PATH toolchain_file NORMALIZE OUTPUT_VARIABLE tc_path)
        file(SHA256 "${tc_path}" tc_sha)
    endif()

    set(input
        "cmake-version|${CMAKE_VERSION}|generator|${generator}|build-type|${build_type}|"
        "toolchain-path|${tc_path}|toolchain-sha|${tc_sha}"
    )
    string(SHA256 full "${input}")
    string(SUBSTRING "${full}" 0 16 key)

    set(${out_key} "${key}")
    return(PROPAGATE ${out_key})
endfunction()

# .. rst:
# ``_cdpm_orchestrator_tail_errors(<build_dir> <out_tail>)``
#
# Reads the configure log (CMakeConfigureLog.yaml preferred, CMakeFiles/CMakeError.log fallback) and
# returns up to 15 lines starting at the first ``CMake Error``. Returns an empty string when no log or
# no error marker is present.
function(_cdpm_orchestrator_tail_errors build_dir out_tail)
    set(candidate_logs "")
    if(EXISTS "${build_dir}/CMakeFiles/CMakeConfigureLog.yaml")
        list(APPEND candidate_logs "${build_dir}/CMakeFiles/CMakeConfigureLog.yaml")
    endif()
    if(EXISTS "${build_dir}/CMakeFiles/CMakeError.log")
        list(APPEND candidate_logs "${build_dir}/CMakeFiles/CMakeError.log")
    endif()

    set(tail "")
    foreach(log_path IN LISTS candidate_logs)
        file(READ "${log_path}" log_content)
        string(FIND "${log_content}" "CMake Error" error_pos)
        if(NOT error_pos EQUAL -1)
            string(SUBSTRING "${log_content}" ${error_pos} -1 from_error)
            string(REPLACE "\n" ";" lines "${from_error}")
            set(selected "")
            set(count 0)
            foreach(line IN LISTS lines)
                if(count GREATER_EQUAL 15)
                    break()
                endif()
                list(APPEND selected "${line}")
                math(EXPR count "${count} + 1")
            endforeach()
            list(JOIN selected "\n" tail)
            break()
        endif()
    endforeach()

    set(${out_tail} "${tail}")
    return(PROPAGATE ${out_tail})
endfunction()

# .. rst:
# ``_cdpm_orchestrator_generate_cmakelists(<src_dir> <command> <pkg> <version>)``
#
# Writes the orchestrator ``CMakeLists.txt`` plus a top-level-includes helper. The helper installs the
# cdpm dependency provider before ``project()`` (required by ``cmake_language(SET_DEPENDENCY_PROVIDER)``)
# and triggers Phase-1 language canonicalization. The ``CMakeLists.txt`` then calls the resolver for the
# requested command. For ``provision`` it reads the lockfile, enumerates roots and runs VERIFY
# validate-only followed by a full VERIFY build pass inside the same configure.
function(_cdpm_orchestrator_generate_cmakelists src_dir command pkg version)
    set(top_includes "# Auto-generated by cdpm. Top-level includes for the orchestrator project.")
    list(APPEND top_includes "set(CDPM_INJECT_ROOT \"${__CDPM_ORCHESTRATOR_ROOT}\" CACHE PATH \"cdpm root\" FORCE)")
    list(APPEND top_includes "set(__cdpm_user_module_path \"\")")
    list(APPEND top_includes "if(DEFINED CACHE{CMAKE_MODULE_PATH})")
    list(APPEND top_includes "    set(__cdpm_user_module_path \"$CACHE{CMAKE_MODULE_PATH}\")")
    list(APPEND top_includes "endif()")
    list(APPEND top_includes "list(PREPEND CMAKE_MODULE_PATH \"${__CDPM_ORCHESTRATOR_CORE_DIR}\")")
    list(APPEND top_includes "include(\"${__CDPM_ORCHESTRATOR_ROOT}/cdpm.cmake\")")
    list(APPEND top_includes "if(NOT __cdpm_user_module_path STREQUAL \"\")")
    list(APPEND top_includes "    list(APPEND CMAKE_MODULE_PATH \${__cdpm_user_module_path})")
    list(APPEND top_includes "endif()")
    list(JOIN top_includes "\n" top_includes_content)
    file(WRITE "${src_dir}/cdpm_top_includes.cmake" "${top_includes_content}\n")

    set(lines "cmake_minimum_required(VERSION 3.25)")
    list(APPEND lines "set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES \"${src_dir}/cdpm_top_includes.cmake\")")
    list(APPEND lines "project(cdpm_orchestrator LANGUAGES C)")
    list(APPEND lines "include(cdpm_lockfile)")
    list(APPEND lines "include(cdpm_resolve)")

    if(command STREQUAL "provision")
        list(APPEND lines "if(DEFINED CDPM_LOCKFILE_PATH AND NOT CDPM_LOCKFILE_PATH STREQUAL \"\")")
        list(APPEND lines "    cdpm_read_lockfile(PATH \"\${CDPM_LOCKFILE_PATH}\")")
        list(APPEND lines "else()")
        list(APPEND lines "    cdpm_read_lockfile()")
        list(APPEND lines "endif()")
        list(APPEND lines "get_property(lock GLOBAL PROPERTY CDPM_LOCKFILE_JSON)")
        list(APPEND lines "_cdpm_lockfile_get_roots(\"\${lock}\" roots)")
        list(APPEND lines "foreach(root IN LISTS roots)")
        list(APPEND lines "    string(JSON ver GET \"\${lock}\" packages \${root} version)")
        list(APPEND lines "    cdpm_resolve_and_build(\${root} \"\${ver}\" ctx LOCK_MODE VERIFY VALIDATE_ONLY)")
        list(APPEND lines "endforeach()")
        list(APPEND lines "foreach(root IN LISTS roots)")
        list(APPEND lines "    string(JSON ver GET \"\${lock}\" packages \${root} version)")
        list(APPEND lines "    cdpm_resolve_and_build(\${root} \"\${ver}\" ctx LOCK_MODE VERIFY)")
        list(APPEND lines "endforeach()")
    else()
        list(APPEND lines "cdpm_resolve_and_build(\"${pkg}\" \"${version}\" ctx LOCK_MODE UPDATE)")
    endif()

    list(JOIN lines "\n" content)
    file(WRITE "${src_dir}/CMakeLists.txt" "${content}\n")
endfunction()

# .. rst:
# ``_cdpm_orchestrator_forward_cache_args(<out_list>)``
#
# Collects every ``CDPM_*`` cache variable (except provider-internal replay guards) so the orchestrator
# project sees the same CLI overrides, store/runtime paths and lockfile flags as the script invocation.
# ``CDPM_LOCKFILE_PATH``, ``CDPM_PROJECT_DIR`` and ``CDPM_SKIP_LOCKFILE`` are handled explicitly by the
# caller (with ``-D``/``-U`` pairs) and are skipped here to avoid duplicate or stale cache entries.
function(_cdpm_orchestrator_forward_cache_args out_list)
    set(result "")
    get_cmake_property(vars CACHE_VARIABLES)
    foreach(var IN LISTS vars)
        if(var MATCHES "^CDPM_" AND NOT var MATCHES "^CDPM_PROVIDER_"
                AND NOT var MATCHES "^CDPM_(LOCKFILE_PATH|PROJECT_DIR|SKIP_LOCKFILE)$")
            get_property(val CACHE "${var}" PROPERTY VALUE)
            get_property(type CACHE "${var}" PROPERTY TYPE)
            if(type STREQUAL "")
                set(type "STRING")
            endif()
            if(NOT val STREQUAL "")
                list(APPEND result "-D${var}:${type}=${val}")
            endif()
        endif()
    endforeach()
    set(${out_list} "${result}")
    return(PROPAGATE ${out_list})
endfunction()

# .. rst:
# ``cdpm_orchestrator_run(<command> <pkg> [<version>] [LOCKFILE <path>] [VERIFY])``
#
# Drives ``install`` or ``provision`` through a generated orchestrator project. ``<pkg>`` is ignored for
# ``provision``. ``LOCKFILE`` overrides the default lockfile path; ``VERIFY`` is implied for ``provision``.
# The orchestrator build directory is serialized with ``file(LOCK)`` per environment key.
function(cdpm_orchestrator_run command pkg)
    set(rest "${ARGN}")
    set(version "")
    set(lockfile "")

    list(LENGTH rest n)
    set(i 0)
    while(i LESS n)
        list(GET rest ${i} token)
        if(token STREQUAL "LOCKFILE")
            math(EXPR i "${i} + 1")
            list(GET rest ${i} lockfile)
            math(EXPR i "${i} + 1")
        elseif(token STREQUAL "VERIFY")
            math(EXPR i "${i} + 1")
        elseif(version STREQUAL "")
            set(version "${token}")
            math(EXPR i "${i} + 1")
        else()
            message(FATAL_ERROR "[cdpm] cdpm_orchestrator_run: unexpected argument '${token}'")
        endif()
    endwhile()

    if(NOT command MATCHES [[^(install|provision)$]])
        message(FATAL_ERROR "[cdpm] cdpm_orchestrator_run: command must be install or provision.")
    endif()

    _cdpm_resolve_project_dir(project_dir)
    _cdpm_resolve_store_dir(store)

    set(toolchain "")
    if(DEFINED CMAKE_TOOLCHAIN_FILE AND NOT CMAKE_TOOLCHAIN_FILE STREQUAL "")
        set(toolchain "${CMAKE_TOOLCHAIN_FILE}")
    endif()
    set(generator "")
    if(DEFINED CMAKE_GENERATOR AND NOT CMAKE_GENERATOR STREQUAL "")
        set(generator "${CMAKE_GENERATOR}")
    endif()
    set(build_type "Release")
    if(DEFINED CMAKE_BUILD_TYPE AND NOT CMAKE_BUILD_TYPE STREQUAL "")
        set(build_type "${CMAKE_BUILD_TYPE}")
    endif()

    _cdpm_orchestrator_env_key("${generator}" "${build_type}" "${toolchain}" env_key)

    set(orch_dir "${store}/.orchestrator/${env_key}")
    set(src_dir "${orch_dir}/src")
    set(build_dir "${orch_dir}/build")
    file(MAKE_DIRECTORY "${orch_dir}")

    file(LOCK "${orch_dir}/.lock" GUARD PROCESS TIMEOUT 3600 RESULT_VARIABLE lock_result)
    if(NOT lock_result EQUAL 0)
        message(FATAL_ERROR
            "[cdpm] orchestrator env-key ${env_key} is locked by another invocation "
            "(gave up after 1 hour)."
        )
    endif()

    _cdpm_orchestrator_generate_cmakelists("${src_dir}" "${command}" "${pkg}" "${version}")

    set(configure_cmd "${CMAKE_COMMAND}" -S "${src_dir}" -B "${build_dir}")
    if(NOT generator STREQUAL "")
        list(APPEND configure_cmd -G "${generator}")
    endif()
    list(APPEND configure_cmd "-DCMAKE_BUILD_TYPE=${build_type}")
    if(NOT toolchain STREQUAL "")
        list(APPEND configure_cmd "-DCMAKE_TOOLCHAIN_FILE=${toolchain}")
    endif()
    if(DEFINED CMAKE_PREFIX_PATH AND NOT CMAKE_PREFIX_PATH STREQUAL "")
        list(APPEND configure_cmd "-DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}")
    endif()
    if(DEFINED CMAKE_MODULE_PATH AND NOT CMAKE_MODULE_PATH STREQUAL "")
        list(APPEND configure_cmd "-DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}")
    endif()

    # Forwarded cache variables come before every explicit argument below: when both set the same
    # variable, the later explicit -D wins, so a stale forwarded value can never override intent.
    _cdpm_orchestrator_forward_cache_args(forward_args)
    if(forward_args)
        list(APPEND configure_cmd ${forward_args})
    endif()

    # Explicit arguments (highest precedence).
    list(APPEND configure_cmd "-DCDPM_PROJECT_DIR=${project_dir}")
    if(NOT lockfile STREQUAL "")
        cmake_path(ABSOLUTE_PATH lockfile BASE_DIRECTORY "${project_dir}" NORMALIZE
            OUTPUT_VARIABLE lockfile_abs)
        list(APPEND configure_cmd "-DCDPM_LOCKFILE_PATH=${lockfile_abs}")
    else()
        # The env-key build directory is shared across commands; purge the lockfile path left by a
        # previous run (e.g. "provision --lockfile X") so this invocation does not silently read X.
        list(APPEND configure_cmd -UCDPM_LOCKFILE_PATH)
    endif()
    if(CDPM_SKIP_LOCKFILE)
        list(APPEND configure_cmd "-DCDPM_SKIP_LOCKFILE:BOOL=TRUE")
    else()
        # Same stale-cache concern as CDPM_LOCKFILE_PATH: drop a leftover --no-lockfile pin.
        list(APPEND configure_cmd -UCDPM_SKIP_LOCKFILE)
    endif()

    # Regular variables from the script invocation must be forwarded explicitly because the orchestrator
    # is a fresh CMake process.
    foreach(var IN ITEMS CDPM_STORE_DIR CDPM_RUNTIME_DIR CDPM_MACHINE_CONFIG CDPM_PROJECT_CONFIG CDPM_USER_CONFIG)
        if(DEFINED ${var} AND NOT "${${var}}" STREQUAL "")
            list(APPEND configure_cmd "-D${var}=${${var}}")
        endif()
    endforeach()

    message(STATUS "[cdpm] orchestrator env-key ${env_key}: configuring ${command} ...")
    execute_process(
        COMMAND ${configure_cmd}
        RESULT_VARIABLE rc
    )

    if(NOT rc EQUAL 0)
        _cdpm_orchestrator_tail_errors("${build_dir}" tail)
        set(repro "cmake -S \"${src_dir}\" -B \"${build_dir}\"")
        if(NOT generator STREQUAL "")
            string(APPEND repro " -G \"${generator}\"")
        endif()
        if(NOT toolchain STREQUAL "")
            string(APPEND repro " -DCMAKE_TOOLCHAIN_FILE=\"${toolchain}\"")
        endif()
        string(APPEND repro " -DCDPM_PROJECT_DIR=\"${project_dir}\"")

        message(FATAL_ERROR
            "[cdpm] orchestrator configure exited with code ${rc}; the command did not complete. "
            "Packages whose builds finished during this configure may already be in the store; "
            "re-running reuses them.\n"
            "Reproduce with:\n  ${repro}\n"
            "Last errors:\n${tail}\n"
            "Likely causes:\n"
            "  - invalid toolchain or missing SDK: re-run the reproduce command and check toolchain output\n"
            "  - generator unavailable: verify 'cmake --help' lists '${generator}'\n"
            "Full logs: ${build_dir}/CMakeFiles/CMakeError.log (or CMakeConfigureLog.yaml)\n"
            "The orchestrator is a plain CMake project; configure it by hand to debug."
        )
    endif()

    message(STATUS "[cdpm] orchestrator env-key ${env_key}: ${command} complete.")
endfunction()
