# cdpm_resolve.cmake - Managed dependency graph resolution and build orchestration.

include_guard(GLOBAL)

cmake_policy(SET CMP0140 NEW)
cmake_policy(SET CMP0054 NEW)

include(cdpm_build)
include(cdpm_lockfile)
include(cdpm_system_dependencies)

function(_cdpm_resolver_set_map_member property key value)
    get_property(map GLOBAL PROPERTY "${property}")
    if(NOT map)
        set(map "{}")
    endif()
    string(JSON map SET "${map}" "${key}" "${value}")
    set_property(GLOBAL PROPERTY "${property}" "${map}")
endfunction()

function(_cdpm_resolver_resolve_node role package_name requested_version out_record)
    string(TOUPPER "${role}" role)
    cdpm_find_package_in_repo("${package_name}" found package_key meta)
    if(NOT found)
        message(FATAL_ERROR "[cdpm] managed dependency '${package_name}' was not found in the loaded repository.")
    endif()
    string(TOLOWER "${package_key}" node_key)
    string(TOLOWER "${role}" role_key)
    set(identity_key "${role_key}:${node_key}")

    get_property(statuses GLOBAL PROPERTY __CDPM_RESOLVER_STATUSES)
    string(JSON status ERROR_VARIABLE status_err GET "${statuses}" "${identity_key}")
    if(NOT status_err AND status STREQUAL "visiting")
        get_property(stack GLOBAL PROPERTY __CDPM_RESOLVER_STACK)
        list(FIND stack "${identity_key}" cycle_start)
        list(SUBLIST stack ${cycle_start} -1 cycle)
        list(APPEND cycle "${identity_key}")
        list(JOIN cycle " -> " cycle_path)
        message(FATAL_ERROR "[cdpm] managed dependency cycle: ${cycle_path}")
    endif()
    if(NOT status_err AND status STREQUAL "done")
        get_property(records GLOBAL PROPERTY __CDPM_RESOLVER_RECORDS)
        string(JSON record GET "${records}" "${identity_key}")
        string(JSON selected_version GET "${record}" version)
        string(JSON compatibility ERROR_VARIABLE compatibility_err GET "${record}" compat_version)
        if(compatibility_err)
            set(compatibility "")
        endif()
        if(NOT requested_version STREQUAL "")
            _cdpm_version_satisfies("${requested_version}" "${compatibility}" "${selected_version}" compatible)
            if(NOT compatible)
                message(FATAL_ERROR "[cdpm] managed dependency version conflict for '${identity_key}': already "
                    "resolved to '${selected_version}', but another edge requests '${requested_version}'.")
            endif()
        endif()
        set(${out_record} "${record}")
        return(PROPAGATE ${out_record})
    endif()

    _cdpm_json_set_safe("${statuses}" "${identity_key}" visiting STRING statuses)
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STATUSES "${statuses}")
    get_property(stack GLOBAL PROPERTY __CDPM_RESOLVER_STACK)
    list(APPEND stack "${identity_key}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STACK "${stack}")

    if(role STREQUAL "HOST")
        cdpm_resolve_version("${node_key}" "${meta}" "${requested_version}" version compatibility HOST)
    else()
        cdpm_resolve_version("${node_key}" "${meta}" "${requested_version}" version compatibility)
    endif()
    cdpm_get_package_dependencies("${node_key}" "${meta}" "${version}" dependencies)
    cdpm_get_package_host_dependencies("${node_key}" "${meta}" "${version}" host_dependencies)
    string(JSON target_dependency_count LENGTH "${dependencies}")
    if(role STREQUAL "HOST" AND target_dependency_count GREATER 0)
        message(FATAL_ERROR "[cdpm] host package '${node_key}' declares target dependencies; host nodes may "
            "resolve only host_dependencies.")
    endif()
    set(dependency_identities "{}")
    set(host_dependency_identities "{}")
    foreach(edge_role IN ITEMS HOST TARGET)
        if(edge_role STREQUAL "TARGET")
            if(role STREQUAL "HOST")
                continue()
            endif()
            set(edge_map "${dependencies}")
            set(identity_map dependency_identities)
        else()
            set(edge_map "${host_dependencies}")
            set(identity_map host_dependency_identities)
        endif()
        _cdpm_json_keys(dependency_names "${edge_map}")
        foreach(dependency_name IN LISTS dependency_names)
        string(JSON dependency_spec GET "${edge_map}" "${dependency_name}")
        string(JSON dependency_version ERROR_VARIABLE dependency_version_err GET "${dependency_spec}" version)
        if(dependency_version_err)
            set(dependency_version "")
        endif()
        _cdpm_resolver_resolve_node("${edge_role}" "${dependency_name}" "${dependency_version}" child_record)
        string(JSON child_key GET "${child_record}" package_key)
        string(JSON duplicate ERROR_VARIABLE duplicate_err GET "${${identity_map}}" "${child_key}")
        if(NOT duplicate_err)
            message(FATAL_ERROR "[cdpm] package '${node_key}': managed dependency keys resolve more than once to "
                "${edge_role} registry package '${child_key}' (duplicate alias or conflicting declaration).")
        endif()
        string(JSON child_version GET "${child_record}" version)
        string(JSON child_hash GET "${child_record}" config_hash)

        set(identity "{}")
        _cdpm_json_set_safe("${identity}" package "${child_key}" STRING identity)
        _cdpm_json_set_safe("${identity}" version "${child_version}" STRING identity)
        _cdpm_json_set_safe("${identity}" config_hash "${child_hash}" STRING identity)
        string(JSON components ERROR_VARIABLE components_err GET "${dependency_spec}" components)
        if(edge_role STREQUAL "TARGET" AND NOT components_err)
            string(JSON identity SET "${identity}" components "${components}")
        endif()
        string(JSON ${identity_map} SET "${${identity_map}}" "${child_key}" "${identity}")
        endforeach()
    endforeach()
    get_property(child_prefixes GLOBAL PROPERTY __CDPM_RESOLVER_PREFIXES)
    list(REMOVE_DUPLICATES child_prefixes)
    get_property(host_prefixes GLOBAL PROPERTY __CDPM_RESOLVER_HOST_PREFIXES)
    list(REMOVE_DUPLICATES host_prefixes)

    set(saved_prefix_path "${CMAKE_PREFIX_PATH}")
    if(child_prefixes)
        list(PREPEND CMAKE_PREFIX_PATH ${child_prefixes})
    endif()
    cdpm_get_package_system_dependencies("${node_key}" "${meta}" "${version}" system_dependencies)
    string(JSON system_count LENGTH "${system_dependencies}")
    if(system_count GREATER 0)
        cdpm_probe_system_dependencies("${node_key}" "${system_dependencies}" system_identities)
    else()
        set(system_identities "{}")
    endif()

    string(JSON dependency_count LENGTH "${dependency_identities}")
    string(JSON host_dependency_count LENGTH "${host_dependency_identities}")
    set(hash_args "")
    if(dependency_count GREATER 0)
        list(APPEND hash_args DEPENDENCY_IDENTITIES "${dependency_identities}")
    endif()
    if(host_dependency_count GREATER 0)
        list(APPEND hash_args HOST_DEPENDENCY_IDENTITIES "${host_dependency_identities}")
    endif()
    if(system_count GREATER 0)
        list(APPEND hash_args SYSTEM_IDENTITIES "${system_identities}")
    endif()
    if(role STREQUAL "HOST")
        cdpm_compute_config_hash("${node_key}" "${version}" "${meta}" config_hash HOST ${hash_args})
    else()
        cdpm_compute_config_hash("${node_key}" "${version}" "${meta}" config_hash ${hash_args})
    endif()

    # Nested-context canary: a nested UPDATE whose computed hash disagrees with the top-level
    # lockfile entry means the two contexts would produce different store slots for the same
    # package - surface that loudly instead of silently duplicating builds.
    get_property(nested_canary GLOBAL PROPERTY __CDPM_RESOLVER_NESTED)
    get_property(lock_mode_canary GLOBAL PROPERTY __CDPM_RESOLVER_LOCK_MODE)
    if(nested_canary AND lock_mode_canary STREQUAL "UPDATE")
        if(role STREQUAL "HOST")
            cdpm_lockfile_get("${node_key}" locked locked_entry HOST)
        else()
            cdpm_lockfile_get("${node_key}" locked locked_entry)
        endif()
        if(locked)
            string(JSON locked_hash ERROR_VARIABLE locked_hash_err GET "${locked_entry}" config_hash)
            if(NOT locked_hash_err AND NOT locked_hash STREQUAL config_hash)
                message(WARNING "[cdpm] nested UPDATE config hash mismatch for '${node_key}': "
                    "lockfile=${locked_hash} computed=${config_hash}")
            endif()
        endif()
    endif()

    get_property(validate_only GLOBAL PROPERTY __CDPM_RESOLVER_VALIDATE_ONLY)
    if(validate_only)
        _cdpm_resolve_store_dir(store NO_CREATE)
    else()
        _cdpm_resolve_store_dir(store)
    endif()
    set(install_dir "${store}/${node_key}/${config_hash}")

    cdpm_get_package_source("${node_key}" "${meta}" "${version}" source dev)
    set(lock_args "")
    if(dependency_count GREATER 0)
        list(APPEND lock_args DEPENDENCIES "${dependency_identities}")
    endif()
    if(host_dependency_count GREATER 0)
        list(APPEND lock_args HOST_DEPENDENCIES "${host_dependency_identities}")
    endif()
    if(system_count GREATER 0)
        list(APPEND lock_args SYSTEM_IDENTITIES "${system_identities}")
    endif()
    _cdpm_lockfile_compose_entry("${version}" "${config_hash}" "${source}" "${dev}" candidate_entry
        ${lock_args})
    get_property(lock_mode GLOBAL PROPERTY __CDPM_RESOLVER_LOCK_MODE)
    if(lock_mode STREQUAL "VERIFY")
        if(role STREQUAL "HOST")
            cdpm_lockfile_get("${node_key}" locked locked_entry HOST)
        else()
            cdpm_lockfile_get("${node_key}" locked locked_entry)
        endif()
        if(NOT locked)
            message(FATAL_ERROR "[cdpm] provision verification failed for '${node_key}': lock entry is missing.")
        endif()
        string(JSON locked_dev ERROR_VARIABLE locked_dev_err GET "${locked_entry}" dev)
        if(NOT locked_dev_err AND locked_dev)
            message(FATAL_ERROR "[cdpm] provision verification failed for '${node_key}': dev:true lock entries "
                "are not reproducible.")
        endif()
        cdpm_canonical_json("${locked_entry}" locked_entry)
        string(JSON entries_equal ERROR_VARIABLE equality_err EQUAL "${locked_entry}" "${candidate_entry}")
        if(equality_err OR NOT entries_equal)
            message(FATAL_ERROR "[cdpm] provision verification failed for '${node_key}': pinned version, source "
                "identity, dependencies, system dependencies, or config hash differs from the current candidate.")
        endif()
    else()
        if(role STREQUAL "HOST")
            _cdpm_resolver_set_map_member(__CDPM_RESOLVER_STAGED_HOST_ENTRIES "${node_key}" "${candidate_entry}")
        else()
            _cdpm_resolver_set_map_member(__CDPM_RESOLVER_STAGED_ENTRIES "${node_key}" "${candidate_entry}")
        endif()
    endif()

    if(lock_mode STREQUAL "UPDATE")
        cdpm_build_dependency("${node_key}" "${version}" "${config_hash}" "${meta}"
            PROFILE "${role}" HOST_PREFIXES "${host_prefixes}")
    endif()
    set(CMAKE_PREFIX_PATH "${saved_prefix_path}")

    cdpm_get_package_find_name("${node_key}" "${meta}" find_name)
    set(record "{}")
    foreach(field package_key version compat_version config_hash install_dir find_name)
        if(field STREQUAL "package_key")
            set(value "${node_key}")
        elseif(field STREQUAL "compat_version")
            set(value "${compatibility}")
        else()
            set(value "${${field}}")
        endif()
        _cdpm_json_set_safe("${record}" "${field}" "${value}" STRING record)
    endforeach()
    _cdpm_resolver_set_map_member(__CDPM_RESOLVER_RECORDS "${identity_key}" "${record}")
    if(role STREQUAL "HOST")
        _cdpm_resolver_set_map_member(__CDPM_RESOLVER_HOST_RECORDS "${node_key}" "${record}")
    else()
        _cdpm_resolver_set_map_member(__CDPM_RESOLVER_TARGET_RECORDS "${node_key}" "${record}")
    endif()
    _cdpm_resolver_set_map_member(__CDPM_RESOLVER_METAS "${identity_key}" "${meta}")
    get_property(build_order GLOBAL PROPERTY __CDPM_RESOLVER_BUILD_ORDER)
    list(APPEND build_order "${identity_key}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_BUILD_ORDER "${build_order}")
    get_property(statuses GLOBAL PROPERTY __CDPM_RESOLVER_STATUSES)
    _cdpm_json_set_safe("${statuses}" "${identity_key}" done STRING statuses)
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STATUSES "${statuses}")
    get_property(stack GLOBAL PROPERTY __CDPM_RESOLVER_STACK)
    list(POP_BACK stack)
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STACK "${stack}")
    if(role STREQUAL "HOST")
        get_property(prefixes GLOBAL PROPERTY __CDPM_RESOLVER_HOST_PREFIXES)
        list(APPEND prefixes "${install_dir}")
        set_property(GLOBAL PROPERTY __CDPM_RESOLVER_HOST_PREFIXES "${prefixes}")
    else()
        get_property(prefixes GLOBAL PROPERTY __CDPM_RESOLVER_PREFIXES)
        list(APPEND prefixes "${install_dir}")
        set_property(GLOBAL PROPERTY __CDPM_RESOLVER_PREFIXES "${prefixes}")
    endif()

    set(${out_record} "${record}")
    return(PROPAGATE ${out_record})
endfunction()

function(_cdpm_resolver_build_verified_graph)
    get_property(records GLOBAL PROPERTY __CDPM_RESOLVER_RECORDS)
    get_property(metas GLOBAL PROPERTY __CDPM_RESOLVER_METAS)
    get_property(build_order GLOBAL PROPERTY __CDPM_RESOLVER_BUILD_ORDER)
    set(prefixes "")
    set(host_prefixes "")
    foreach(identity_key IN LISTS build_order)
        string(REPLACE ":" ";" identity_parts "${identity_key}")
        list(GET identity_parts 0 role)
        list(GET identity_parts 1 package_key)
        string(TOUPPER "${role}" role)
        string(JSON record GET "${records}" "${identity_key}")
        string(JSON version GET "${record}" version)
        string(JSON config_hash GET "${record}" config_hash)
        string(JSON install_dir GET "${record}" install_dir)
        string(JSON meta GET "${metas}" "${identity_key}")
        set(saved_prefix_path "${CMAKE_PREFIX_PATH}")
        if(prefixes)
            list(PREPEND CMAKE_PREFIX_PATH ${prefixes})
        endif()
        cdpm_build_dependency("${package_key}" "${version}" "${config_hash}" "${meta}"
            PROFILE "${role}" HOST_PREFIXES "${host_prefixes}")
        set(CMAKE_PREFIX_PATH "${saved_prefix_path}")
        if(role STREQUAL "HOST")
            list(APPEND host_prefixes "${install_dir}")
        else()
            list(APPEND prefixes "${install_dir}")
        endif()
    endforeach()
endfunction()

# .. rst:
# ``cdpm_resolve_and_build(<pkg_name> <requested_version> <out_context_json>
#                          [LOCK_MODE UPDATE|VERIFY] [VALIDATE_ONLY] [ROLE TARGET|HOST])``
function(cdpm_resolve_and_build pkg_name requested_version out_context_json)
    cmake_parse_arguments(arg "VALIDATE_ONLY" "LOCK_MODE;ROLE" "" ${ARGN})
    if(NOT DEFINED arg_LOCK_MODE OR arg_LOCK_MODE STREQUAL "")
        set(arg_LOCK_MODE UPDATE)
    endif()
    string(TOUPPER "${arg_LOCK_MODE}" arg_LOCK_MODE)
    if(NOT arg_LOCK_MODE MATCHES [[^(UPDATE|VERIFY)$]])
        message(FATAL_ERROR "[cdpm] cdpm_resolve_and_build: LOCK_MODE must be UPDATE or VERIFY.")
    endif()
    if(arg_VALIDATE_ONLY AND NOT arg_LOCK_MODE STREQUAL "VERIFY")
        message(FATAL_ERROR "[cdpm] cdpm_resolve_and_build: VALIDATE_ONLY requires LOCK_MODE VERIFY.")
    endif()
    if(NOT DEFINED arg_ROLE OR arg_ROLE STREQUAL "")
        set(arg_ROLE TARGET)
    endif()
    string(TOUPPER "${arg_ROLE}" arg_ROLE)
    if(NOT arg_ROLE MATCHES [[^(TARGET|HOST)$]])
        message(FATAL_ERROR "[cdpm] cdpm_resolve_and_build: ROLE must be TARGET or HOST.")
    endif()

    get_property(nested GLOBAL PROPERTY __CDPM_RESOLVER_NESTED)

    cdpm_config_load()
    get_property(lock_loaded GLOBAL PROPERTY CDPM_LOCKFILE_LOADED)
    if(NOT lock_loaded)
        cdpm_read_lockfile()
    endif()
    _cdpm_lockfile_collect_git_repos(current_repo_pins)
    if(arg_LOCK_MODE STREQUAL "VERIFY")
        get_property(lock GLOBAL PROPERTY CDPM_LOCKFILE_JSON)
        string(JSON locked_repo_pins ERROR_VARIABLE locked_repos_err GET "${lock}" repos)
        if(locked_repos_err)
            set(locked_repo_pins "[]")
        endif()
        cdpm_canonical_json("${locked_repo_pins}" locked_repo_pins)
        string(JSON repos_equal ERROR_VARIABLE repos_equal_err EQUAL
            "${locked_repo_pins}" "${current_repo_pins}")
        if(repos_equal_err OR NOT repos_equal)
            message(FATAL_ERROR "[cdpm] provision verification failed: configured git repository pins differ "
                "from lockfile repos.")
        endif()
    endif()
    cdpm_load_repos()

    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STATUSES "{}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_RECORDS "{}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_TARGET_RECORDS "{}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_HOST_RECORDS "{}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STACK "")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_PREFIXES "")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_HOST_PREFIXES "")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STAGED_ENTRIES "{}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_STAGED_HOST_ENTRIES "{}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_LOCK_MODE "${arg_LOCK_MODE}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_METAS "{}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_BUILD_ORDER "")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_VALIDATE_ONLY "${arg_VALIDATE_ONLY}")
    set_property(GLOBAL PROPERTY __CDPM_RESOLVER_NESTED "${nested}")
    _cdpm_resolver_resolve_node("${arg_ROLE}" "${pkg_name}" "${requested_version}" root_record)

    if(arg_LOCK_MODE STREQUAL "UPDATE" AND NOT nested)
        get_property(staged_entries GLOBAL PROPERTY __CDPM_RESOLVER_STAGED_ENTRIES)
        get_property(staged_host_entries GLOBAL PROPERTY __CDPM_RESOLVER_STAGED_HOST_ENTRIES)
        _cdpm_lockfile_commit_entries("${staged_entries}" HOST_ENTRIES "${staged_host_entries}"
            REPOS "${current_repo_pins}")
    elseif(NOT arg_VALIDATE_ONLY)
        _cdpm_resolver_build_verified_graph()
    endif()

    get_property(records GLOBAL PROPERTY __CDPM_RESOLVER_TARGET_RECORDS)
    get_property(host_records GLOBAL PROPERTY __CDPM_RESOLVER_HOST_RECORDS)
    get_property(prefixes GLOBAL PROPERTY __CDPM_RESOLVER_PREFIXES)
    get_property(host_prefixes GLOBAL PROPERTY __CDPM_RESOLVER_HOST_PREFIXES)
    set(prefixes_json "[]")
    set(host_prefixes_json "[]")
    set(i 0)
    foreach(prefix IN LISTS prefixes)
        _cdpm_json_set_safe("${prefixes_json}" ${i} "${prefix}" STRING prefixes_json)
        math(EXPR i "${i} + 1")
    endforeach()
    set(i 0)
    foreach(prefix IN LISTS host_prefixes)
        _cdpm_json_set_safe("${host_prefixes_json}" ${i} "${prefix}" STRING host_prefixes_json)
        math(EXPR i "${i} + 1")
    endforeach()

    set(context "${root_record}")
    string(JSON context SET "${context}" managed "${records}")
    string(JSON context SET "${context}" host_managed "${host_records}")
    string(JSON context SET "${context}" prefixes "${prefixes_json}")
    string(JSON context SET "${context}" host_prefixes "${host_prefixes_json}")
    foreach(property IN ITEMS __CDPM_RESOLVER_STATUSES __CDPM_RESOLVER_RECORDS __CDPM_RESOLVER_STACK
            __CDPM_RESOLVER_TARGET_RECORDS __CDPM_RESOLVER_HOST_RECORDS __CDPM_RESOLVER_PREFIXES
            __CDPM_RESOLVER_HOST_PREFIXES __CDPM_RESOLVER_STAGED_ENTRIES __CDPM_RESOLVER_STAGED_HOST_ENTRIES
            __CDPM_RESOLVER_LOCK_MODE __CDPM_RESOLVER_METAS __CDPM_RESOLVER_BUILD_ORDER
            __CDPM_RESOLVER_VALIDATE_ONLY)
        set_property(GLOBAL PROPERTY "${property}")
    endforeach()
    # __CDPM_RESOLVER_NESTED is deliberately NOT reset here: it is process-environment state owned by
    # cdpm_provider_inject.cmake (TRUE for every resolve inside an ExternalProject child build), not
    # per-call resolver state. Clearing it would silently downgrade all nested resolves after the
    # first one to top-level behaviour, silencing the nested-hash canary and letting child builds
    # commit lockfile entries.
    set(${out_context_json} "${context}")
    return(PROPAGATE ${out_context_json})
endfunction()
