# cdpm_system_dependencies.cmake - Isolated discovery and identity of system packages.

include_guard(GLOBAL)

cmake_policy(SET CMP0140 NEW)

include(cdpm_config)
include(cdpm_context)
include(cdpm_toolchain)

# .. rst:
# ``cdpm_probe_system_dependencies(<pkg_name> <dependencies_json> <out_identities_json>)``
#
# Configures an isolated, offline child project for each declared dependency and returns canonical identity
# records. Discovery receives the parent's toolchain, generator, build type, prefix path, and module path.
function(cdpm_probe_system_dependencies pkg_name dependencies_json out_identities_json)
    _cdpm_normalize_system_dependencies("${pkg_name}" "${dependencies_json}"
        "effective system_dependencies" dependencies)
    _cdpm_resolve_runtime_dir(runtime_dir)

    set(probe_context "{}")
    string(JSON probe_context SET "${probe_context}" declarations "${dependencies}")
    foreach(context_var IN ITEMS
            CMAKE_VERSION
            CMAKE_GENERATOR
            CMAKE_GENERATOR_PLATFORM
            CMAKE_GENERATOR_TOOLSET
            CMAKE_GENERATOR_INSTANCE
            CMAKE_BUILD_TYPE
            CMAKE_PREFIX_PATH
            CMAKE_MODULE_PATH)
        _cdpm_json_set_safe("${probe_context}" "${context_var}" "${${context_var}}" STRING probe_context)
    endforeach()
    if(DEFINED CMAKE_TOOLCHAIN_FILE AND NOT CMAKE_TOOLCHAIN_FILE STREQUAL "")
        set(external_toolchain "${CMAKE_TOOLCHAIN_FILE}")
        cmake_path(ABSOLUTE_PATH external_toolchain NORMALIZE OUTPUT_VARIABLE external_toolchain)
        file(SHA256 "${external_toolchain}" external_toolchain_hash)
        set(toolchain_identity "{}")
        _cdpm_json_set_safe("${toolchain_identity}" path "${external_toolchain}" STRING toolchain_identity)
        _cdpm_json_set_safe("${toolchain_identity}" sha256 "${external_toolchain_hash}" STRING toolchain_identity)
        string(JSON probe_context SET "${probe_context}" external_toolchain "${toolchain_identity}")
    endif()
    _cdpm_toolchain_var_list(toolchain_vars)
    list(SORT toolchain_vars)
    set(frozen_values "{}")
    foreach(var IN LISTS toolchain_vars)
        if(DEFINED ${var})
            _cdpm_json_set_safe("${frozen_values}" "${var}" "${${var}}" STRING frozen_values)
        endif()
    endforeach()
    string(JSON probe_context SET "${probe_context}" frozen_values "${frozen_values}")
    cdpm_canonical_json("${probe_context}" probe_context)
    string(SHA256 probe_key "${probe_context}")
    cdpm_prepare_toolchain("system-probe-${probe_key}" probe_toolchain)

    set(probe_root "${runtime_dir}/system-probe/${probe_key}")
    file(MAKE_DIRECTORY "${probe_root}")

    set(probe_template [=[cmake_minimum_required(VERSION 3.25)
project(cdpm_system_probe NONE)
cmake_policy(SET CMP0140 NEW)

function(json_set_string json key value out)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(JSON json SET "${json}" "${key}" "\"${value}\"")
    set(${out} "${json}" PARENT_SCOPE)
endfunction()

file(READ "${CMAKE_CURRENT_SOURCE_DIR}/request.json" request)
string(JSON package_name GET "${request}" package_name)
string(JSON spec GET "${request}" spec)
string(JSON mode GET "${spec}" mode)
string(JSON requested_version ERROR_VARIABLE version_err GET "${spec}" version)
string(JSON components ERROR_VARIABLE components_err GET "${spec}" components)

set(find_args "${package_name}")
if(NOT version_err)
    list(APPEND find_args "${requested_version}")
endif()
list(APPEND find_args REQUIRED "${mode}")
if(NOT components_err)
    string(JSON component_count LENGTH "${components}")
    if(component_count GREATER 0)
        list(APPEND find_args COMPONENTS)
        math(EXPR component_last "${component_count} - 1")
        foreach(i RANGE 0 ${component_last})
            string(JSON component GET "${components}" ${i})
            list(APPEND find_args "${component}")
        endforeach()
    endif()
endif()

if(mode STREQUAL "MODULE")
    set(definition "")
    foreach(module_dir IN LISTS CMAKE_MODULE_PATH)
        if(EXISTS "${module_dir}/Find${package_name}.cmake")
            set(definition "${module_dir}/Find${package_name}.cmake")
            break()
        endif()
    endforeach()
    if(definition STREQUAL "" AND EXISTS "${CMAKE_ROOT}/Modules/Find${package_name}.cmake")
        set(definition "${CMAKE_ROOT}/Modules/Find${package_name}.cmake")
    endif()
    if(definition STREQUAL "")
        message(FATAL_ERROR "[cdpm] no definition file found for MODULE package '${package_name}'.")
    endif()
endif()

find_package(${find_args})

if(mode STREQUAL "CONFIG")
    set(config_variable "${package_name}_CONFIG")
    set(definition "${${config_variable}}")
endif()
if(definition STREQUAL "" OR NOT EXISTS "${definition}" OR IS_DIRECTORY "${definition}")
    message(FATAL_ERROR "[cdpm] definition file for '${package_name}' is not readable.")
endif()
if(mode STREQUAL "CONFIG")
    cmake_path(GET definition PARENT_PATH definition_root)
    file(GLOB_RECURSE definition_files RELATIVE "${definition_root}" "${definition_root}/*.cmake")
    list(SORT definition_files)
    set(definition_identity "")
    foreach(definition_relative IN LISTS definition_files)
        file(SHA256 "${definition_root}/${definition_relative}" definition_file_hash)
        string(APPEND definition_identity "${definition_relative}=${definition_file_hash}\n")
    endforeach()
    string(SHA256 definition_hash "${definition_identity}")
else()
    file(SHA256 "${definition}" definition_hash)
endif()

set(found_version "")
string(TOUPPER "${package_name}" package_upper)
foreach(version_variable IN ITEMS
        "${package_name}_VERSION" "${package_upper}_VERSION"
        "${package_name}_VERSION_STRING" "${package_upper}_VERSION_STRING")
    if(DEFINED ${version_variable} AND NOT "${${version_variable}}" STREQUAL "")
        set(found_version "${${version_variable}}")
        break()
    endif()
endforeach()
if(NOT version_err AND found_version STREQUAL "")
    message(FATAL_ERROR "[cdpm] package '${package_name}' did not report a version for requested "
        "'${requested_version}'.")
endif()

set(identity "{}")
json_set_string("${identity}" mode "${mode}" identity)
if(version_err)
    json_set_string("${identity}" version "" identity)
else()
    json_set_string("${identity}" version "${requested_version}" identity)
endif()
if(components_err)
    string(JSON identity SET "${identity}" components "[]")
else()
    string(JSON identity SET "${identity}" components "${components}")
endif()
json_set_string("${identity}" found_version "${found_version}" identity)
json_set_string("${identity}" definition_sha256 "${definition_hash}" identity)

set(targets "{}")
set(include_roots "")
string(JSON identity_targets GET "${spec}" identity_targets)
string(JSON target_count LENGTH "${identity_targets}")
math(EXPR target_last "${target_count} - 1")
foreach(i RANGE 0 ${target_last})
    string(JSON target GET "${identity_targets}" ${i})
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "[cdpm] identity target '${target}' does not exist.")
    endif()
    get_target_property(imported "${target}" IMPORTED)
    if(NOT imported)
        message(FATAL_ERROR "[cdpm] identity target '${target}' is not IMPORTED.")
    endif()

    get_target_property(configurations "${target}" IMPORTED_CONFIGURATIONS)
    if(configurations MATCHES "-NOTFOUND$")
        set(configurations "")
    endif()
    list(APPEND configurations DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
    list(REMOVE_DUPLICATES configurations)
    set(properties IMPORTED_LOCATION IMPORTED_IMPLIB)
    foreach(configuration IN LISTS configurations)
        string(TOUPPER "${configuration}" configuration)
        list(APPEND properties "IMPORTED_LOCATION_${configuration}" "IMPORTED_IMPLIB_${configuration}")
    endforeach()
    list(REMOVE_DUPLICATES properties)

    set(target_identity "{}")
    set(artifact_count 0)
    foreach(property IN LISTS properties)
        get_target_property(artifact "${target}" "${property}")
        if(artifact MATCHES "-NOTFOUND$" OR artifact STREQUAL "")
            continue()
        endif()
        if(NOT EXISTS "${artifact}" OR IS_DIRECTORY "${artifact}")
            message(FATAL_ERROR "[cdpm] identity target '${target}' property ${property} has no readable artifact.")
        endif()
        file(SHA256 "${artifact}" artifact_hash)
        json_set_string("${target_identity}" "${property}" "${artifact_hash}" target_identity)
        math(EXPR artifact_count "${artifact_count} + 1")
    endforeach()
    if(artifact_count EQUAL 0)
        message(FATAL_ERROR "[cdpm] identity target '${target}' has no readable imported artifact.")
    endif()
    foreach(property IN ITEMS
            INTERFACE_INCLUDE_DIRECTORIES
            INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
            INTERFACE_COMPILE_DEFINITIONS
            INTERFACE_COMPILE_OPTIONS
            INTERFACE_LINK_LIBRARIES
            INTERFACE_LINK_OPTIONS
            INTERFACE_LINK_DIRECTORIES)
        get_target_property(property_value "${target}" "${property}")
        if(property_value MATCHES "-NOTFOUND$" OR property_value STREQUAL "")
            continue()
        endif()
        string(SHA256 property_hash "${property}=${property_value}")
        json_set_string("${target_identity}" "${property}" "${property_hash}" target_identity)
        if(property MATCHES "^(INTERFACE_INCLUDE_DIRECTORIES|INTERFACE_SYSTEM_INCLUDE_DIRECTORIES)$")
            foreach(include_root IN LISTS property_value)
                if(NOT include_root MATCHES [[\$<]] AND IS_DIRECTORY "${include_root}")
                    cmake_path(ABSOLUTE_PATH include_root NORMALIZE OUTPUT_VARIABLE include_root)
                    list(APPEND include_roots "${include_root}")
                endif()
            endforeach()
        endif()
    endforeach()
    string(JSON targets SET "${targets}" "${target}" "${target_identity}")
endforeach()
string(JSON identity SET "${identity}" targets "${targets}")

string(JSON identity_paths ERROR_VARIABLE identity_paths_err GET "${spec}" identity_paths)
if(NOT identity_paths_err)
    list(REMOVE_DUPLICATES include_roots)
    list(SORT include_roots)
    set(identity_path_hashes "[]")
    string(JSON identity_path_count LENGTH "${identity_paths}")
    if(identity_path_count GREATER 0)
        math(EXPR identity_path_last "${identity_path_count} - 1")
        foreach(i RANGE 0 ${identity_path_last})
            string(JSON identity_path GET "${identity_paths}" ${i})
            set(match_hashes "")
            foreach(include_root IN LISTS include_roots)
                set(candidate "${include_root}/${identity_path}")
                if(IS_SYMLINK "${candidate}")
                    message(FATAL_ERROR "[cdpm] identity path '${identity_path}' resolves to symlink "
                        "'${candidate}'; symlinks are forbidden in identity_paths.")
                endif()
                if(NOT EXISTS "${candidate}")
                    continue()
                endif()
                if(IS_DIRECTORY "${candidate}")
                    file(GLOB_RECURSE candidate_entries
                        LIST_DIRECTORIES TRUE
                        RELATIVE "${candidate}"
                        "${candidate}/*"
                    )
                    list(SORT candidate_entries)
                    set(candidate_identity "")
                    foreach(candidate_relative IN LISTS candidate_entries)
                        set(candidate_file "${candidate}/${candidate_relative}")
                        if(IS_SYMLINK "${candidate_file}")
                            message(FATAL_ERROR "[cdpm] identity path '${identity_path}' contains symlink "
                                "'${candidate_relative}'; symlinks are forbidden in identity_paths.")
                        endif()
                        if(IS_DIRECTORY "${candidate_file}")
                            continue()
                        endif()
                        file(SHA256 "${candidate_file}" candidate_file_hash)
                        string(APPEND candidate_identity "${candidate_relative}=${candidate_file_hash}\n")
                    endforeach()
                    string(SHA256 match_hash "directory\n${candidate_identity}")
                else()
                    file(SHA256 "${candidate}" candidate_file_hash)
                    string(SHA256 match_hash "file\n${candidate_file_hash}")
                endif()
                list(APPEND match_hashes "${match_hash}")
            endforeach()
            if(match_hashes STREQUAL "")
                message(FATAL_ERROR "[cdpm] identity path '${identity_path}' was not found in an identity "
                    "target include directory.")
            endif()
            list(REMOVE_DUPLICATES match_hashes)
            list(SORT match_hashes)
            list(JOIN match_hashes "\n" match_identity)
            string(SHA256 identity_path_hash "${identity_path}\n${match_identity}")
            json_set_string("${identity_path_hashes}" ${i} "${identity_path_hash}" identity_path_hashes)
        endforeach()
    endif()
    string(JSON identity SET "${identity}" identity_paths "${identity_path_hashes}")
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/identity.json" "${identity}")
]=])

    set(identities "{}")
    _cdpm_json_foreach("${dependencies}" dependency_names)
    foreach(dependency_name IN LISTS dependency_names)
        string(JSON spec GET "${dependencies}" "${dependency_name}")
        string(SHA256 dependency_hash "${dependency_name}|${spec}")
        set(source_dir "${probe_root}/${dependency_hash}/src")
        set(binary_dir "${probe_root}/${dependency_hash}/build")
        file(REMOVE_RECURSE "${source_dir}" "${binary_dir}")
        file(MAKE_DIRECTORY "${source_dir}")
        set(request "{}")
        _cdpm_json_set_safe("${request}" "package_name" "${dependency_name}" "STRING" request)
        string(JSON request SET "${request}" "spec" "${spec}")
        file(WRITE "${source_dir}/request.json" "${request}")
        file(WRITE "${source_dir}/CMakeLists.txt" "${probe_template}")

        set(command "${CMAKE_COMMAND}" -S "${source_dir}" -B "${binary_dir}")
        if(NOT "${CMAKE_GENERATOR}" STREQUAL "")
            list(APPEND command -G "${CMAKE_GENERATOR}")
        endif()
        if(NOT "${CMAKE_GENERATOR_PLATFORM}" STREQUAL "")
            list(APPEND command -A "${CMAKE_GENERATOR_PLATFORM}")
        endif()
        if(NOT "${CMAKE_GENERATOR_TOOLSET}" STREQUAL "")
            list(APPEND command -T "${CMAKE_GENERATOR_TOOLSET}")
        endif()
        if(NOT "${CMAKE_GENERATOR_INSTANCE}" STREQUAL "")
            list(APPEND command "-DCMAKE_GENERATOR_INSTANCE:STRING=${CMAKE_GENERATOR_INSTANCE}")
        endif()
        string(REPLACE ";" "\\;" probe_prefix_path "${CMAKE_PREFIX_PATH}")
        string(REPLACE ";" "\\;" probe_module_path "${CMAKE_MODULE_PATH}")
        list(APPEND command
            "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
            "-DCMAKE_PREFIX_PATH:STRING=${probe_prefix_path}"
            "-DCMAKE_MODULE_PATH:STRING=${probe_module_path}"
            -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY:BOOL=ON
            -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY:BOOL=ON
            -DCMAKE_FIND_USE_PACKAGE_REGISTRY:BOOL=OFF
            -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY:BOOL=OFF
            -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON)
        list(APPEND command "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=${probe_toolchain}")
        if(DEFINED CMAKE_MAKE_PROGRAM AND NOT CMAKE_MAKE_PROGRAM STREQUAL "")
            list(APPEND command "-DCMAKE_MAKE_PROGRAM:FILEPATH=${CMAKE_MAKE_PROGRAM}")
        endif()

        execute_process(
            COMMAND ${command}
            RESULT_VARIABLE result
            OUTPUT_VARIABLE output
            ERROR_VARIABLE error
        )
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "[cdpm] system dependency probe for '${dependency_name}' failed:\n${output}${error}")
        endif()
        file(READ "${binary_dir}/identity.json" identity)
        string(JSON identities SET "${identities}" "${dependency_name}" "${identity}")
        file(REMOVE_RECURSE "${source_dir}" "${binary_dir}")
    endforeach()

    cdpm_canonical_json("${identities}" identities)
    set(${out_identities_json} "${identities}")
    return(PROPAGATE ${out_identities_json})
endfunction()
