# cdpm_registry.cmake - Package registry schema readers and private provenance.

include_guard(GLOBAL)

cmake_policy(SET CMP0140 NEW)
cmake_policy(SET CMP0057 NEW)

include(cdpm_utils)
include(cdpm_context)

cmake_path(GET CMAKE_CURRENT_LIST_FILE PARENT_PATH __CDPM_REGISTRY_MODULE_DIR)

# Registry containment assumes that the registry tree is immutable for the complete load, validation, and build.
# Real-path and regular-file checks prevent static traversal and symbolic-link escapes. CMake has no atomic no-follow
# open, so concurrent hostile mutation of the registry tree is outside this trust model.

# CMake 3.25 can distinguish directories and symlinks, but has no regular-file predicate. On POSIX, use the
# standard ``test`` utility without a shell so FIFOs, sockets, and device nodes are rejected before any read.
# Windows has no equivalent guaranteed system utility; after existence/directory checks, ordinary filesystem
# entries are accepted there. Callers must still perform this check immediately before reading or hashing.
if(UNIX)
    find_program(__CDPM_TEST_PROGRAM NAMES test)
endif()

function(_cdpm_registry_require_regular_file path context)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "[cdpm] ${context}: file not found: '${path}'.")
    endif()
    if(IS_DIRECTORY "${path}")
        message(FATAL_ERROR "[cdpm] ${context}: expected a regular file: '${path}'.")
    endif()
    if(UNIX)
        if(NOT __CDPM_TEST_PROGRAM)
            message(FATAL_ERROR "[cdpm] ${context}: cannot safely validate regular file '${path}': the POSIX "
                "'test' utility is unavailable.")
        endif()
        execute_process(COMMAND "${__CDPM_TEST_PROGRAM}" -f "${path}" RESULT_VARIABLE test_result TIMEOUT 5)
        if(NOT test_result EQUAL 0)
            message(FATAL_ERROR "[cdpm] ${context}: expected a regular file, but found a special filesystem "
                "node: '${path}'.")
        endif()
    endif()
endfunction()

# Reads a regular file and verifies that its path, type, and content identity remain stable across the read.
function(_cdpm_registry_read_regular_file path context base_dir out_content out_real_path)
    _cdpm_registry_require_regular_file("${path}" "${context}")
    file(REAL_PATH "${path}" real_path_before)
    if(NOT base_dir STREQUAL "")
        file(REAL_PATH "${base_dir}" real_base)
        cmake_path(IS_PREFIX real_base "${real_path_before}" NORMALIZE contained_before)
        if(NOT contained_before)
            message(FATAL_ERROR "[cdpm] ${context}: path escapes through a symbolic link: '${path}'.")
        endif()
    endif()

    file(READ "${real_path_before}" content)

    _cdpm_registry_require_regular_file("${path}" "${context}")
    file(REAL_PATH "${path}" real_path_after)
    if(NOT real_path_after STREQUAL real_path_before)
        message(FATAL_ERROR "[cdpm] ${context}: file identity changed while it was being read: '${path}'.")
    endif()
    if(NOT base_dir STREQUAL "")
        cmake_path(IS_PREFIX real_base "${real_path_after}" NORMALIZE contained_after)
        if(NOT contained_after)
            message(FATAL_ERROR "[cdpm] ${context}: path escapes through a symbolic link: '${path}'.")
        endif()
    endif()
    file(SHA256 "${real_path_after}" content_hash_after)
    string(SHA256 content_hash "${content}")
    if(NOT content_hash STREQUAL content_hash_after)
        message(FATAL_ERROR "[cdpm] ${context}: file content changed while it was being read: '${path}'.")
    endif()

    set(${out_content} "${content}")
    set(${out_real_path} "${real_path_after}")
    return(PROPAGATE ${out_content} ${out_real_path})
endfunction()

# Resolves an authored registry path and proves that its real path remains below ``base_dir``.
function(_cdpm_registry_resolve_contained_file base_dir authored context out_path)
    if(authored STREQUAL "" OR IS_ABSOLUTE "${authored}"
            OR authored MATCHES "^[A-Za-z]:[/\\\\]"
            OR authored MATCHES "^[/\\\\][/\\\\]")
        message(FATAL_ERROR "[cdpm] ${context}: path must be a non-empty relative path: '${authored}'.")
    endif()
    if(authored MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)")
        message(FATAL_ERROR "[cdpm] ${context}: path must not contain '..': '${authored}'.")
    endif()

    set(candidate "${authored}")
    cmake_path(ABSOLUTE_PATH candidate BASE_DIRECTORY "${base_dir}" NORMALIZE OUTPUT_VARIABLE candidate)
    set(lexical_base "${base_dir}")
    cmake_path(ABSOLUTE_PATH lexical_base NORMALIZE OUTPUT_VARIABLE lexical_base)
    cmake_path(IS_PREFIX lexical_base "${candidate}" NORMALIZE lexically_contained)
    if(NOT lexically_contained)
        message(FATAL_ERROR "[cdpm] ${context}: path escapes its registry base: '${authored}'.")
    endif()
    file(REAL_PATH "${lexical_base}" real_base)
    _cdpm_registry_require_regular_file("${candidate}" "${context}")
    file(REAL_PATH "${candidate}" real_candidate)
    cmake_path(IS_PREFIX real_base "${real_candidate}" NORMALIZE really_contained)
    if(NOT really_contained)
        message(FATAL_ERROR "[cdpm] ${context}: path escapes through a symbolic link: '${authored}'.")
    endif()
    _cdpm_registry_require_regular_file("${candidate}" "${context}")
    file(REAL_PATH "${candidate}" real_candidate_after)
    if(NOT real_candidate_after STREQUAL real_candidate)
        message(FATAL_ERROR "[cdpm] ${context}: file identity changed during validation: '${authored}'.")
    endif()

    set(${out_path} "${real_candidate}")
    return(PROPAGATE ${out_path})
endfunction()

function(_cdpm_registry_validate_relative_path authored context)
    if(authored STREQUAL "" OR IS_ABSOLUTE "${authored}"
            OR authored MATCHES "^[A-Za-z]:[/\\\\]"
            OR authored MATCHES "^[/\\\\][/\\\\]")
        message(FATAL_ERROR "[cdpm] ${context}: path must be a non-empty relative path: '${authored}'.")
    endif()
    if(authored MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)")
        message(FATAL_ERROR "[cdpm] ${context}: path must not contain '..': '${authored}'.")
    endif()
endfunction()

function(_cdpm_registry_set_provenance pkg_name schema repo_root manifest_dir)
    get_property(provenance GLOBAL PROPERTY CDPM_REPO_PROVENANCE)
    if(NOT provenance)
        set(provenance "{}")
    endif()
    set(record "{}")
    string(JSON record SET "${record}" schema "${schema}")
    _cdpm_json_set_safe("${record}" repo_root "${repo_root}" STRING record)
    _cdpm_json_set_safe("${record}" manifest_dir "${manifest_dir}" STRING record)
    string(JSON provenance SET "${provenance}" "${pkg_name}" "${record}")
    set_property(GLOBAL PROPERTY CDPM_REPO_PROVENANCE "${provenance}")
endfunction()

function(_cdpm_registry_get_provenance pkg_name out_found out_json)
    string(TOLOWER "${pkg_name}" name)
    get_property(provenance GLOBAL PROPERTY CDPM_REPO_PROVENANCE)
    if(provenance)
        string(JSON record ERROR_VARIABLE record_err GET "${provenance}" "${name}")
    else()
        set(record_err TRUE)
    endif()
    if(record_err)
        set(${out_found} FALSE)
        set(${out_json} "{}")
    else()
        set(${out_found} TRUE)
        set(${out_json} "${record}")
    endif()
    return(PROPAGATE ${out_found} ${out_json})
endfunction()

# Resolves one effective patch path. Schema 1 intentionally retains project-relative behavior.
function(_cdpm_registry_resolve_patch_path pkg_name authored out_path)
    _cdpm_registry_get_provenance("${pkg_name}" found provenance)
    if(found)
        string(JSON schema GET "${provenance}" schema)
    else()
        set(schema 1)
    endif()

    if(schema EQUAL 2)
        string(JSON manifest_dir GET "${provenance}" manifest_dir)
        _cdpm_registry_resolve_contained_file("${manifest_dir}" "${authored}"
            "schema-2 package '${pkg_name}' patch" resolved)
    else()
        set(resolved "${authored}")
        if(NOT IS_ABSOLUTE "${resolved}")
            _cdpm_resolve_project_dir(project_dir)
            cmake_path(ABSOLUTE_PATH resolved BASE_DIRECTORY "${project_dir}" NORMALIZE OUTPUT_VARIABLE resolved)
        endif()
        if(EXISTS "${resolved}")
            _cdpm_registry_require_regular_file("${resolved}" "schema-1 package '${pkg_name}' patch")
        endif()
    endif()
    set(${out_path} "${resolved}")
    return(PROPAGATE ${out_path})
endfunction()

function(_cdpm_registry_validate_schema2_patch_assets pkg_name pkg_json manifest_dir)
    string(JSON patches ERROR_VARIABLE patches_err GET "${pkg_json}" patches)
    if(NOT patches_err)
        string(JSON patch_count LENGTH "${patches}")
        if(patch_count GREATER 0)
            math(EXPR patch_last "${patch_count} - 1")
            foreach(i RANGE 0 ${patch_last})
                string(JSON authored GET "${patches}" ${i} file)
                _cdpm_registry_resolve_contained_file("${manifest_dir}" "${authored}"
                    "schema-2 package '${pkg_name}' patches[${i}]" unused)
            endforeach()
        endif()
    endif()

    string(JSON versions ERROR_VARIABLE versions_err GET "${pkg_json}" versions)
    if(versions_err)
        return()
    endif()
    _cdpm_json_foreach("${versions}" version_keys)
    foreach(version IN LISTS version_keys)
        string(JSON version_patches ERROR_VARIABLE version_patches_err GET
            "${versions}" "${version}" patches)
        if(version_patches_err)
            continue()
        endif()
        string(JSON patch_count LENGTH "${version_patches}")
        if(patch_count GREATER 0)
            math(EXPR patch_last "${patch_count} - 1")
            foreach(i RANGE 0 ${patch_last})
                string(JSON authored GET "${version_patches}" ${i})
                _cdpm_registry_resolve_contained_file("${manifest_dir}" "${authored}"
                    "schema-2 package '${pkg_name}' versions.${version}.patches[${i}]" unused)
            endforeach()
        endif()
    endforeach()
endfunction()

function(_cdpm_registry_register_package repo_file repo_root schema name pkg_json manifest_dir masks_json)
    cmake_parse_arguments(arg "CLAIMED;SKIP_ALIAS_CHECK" "" "" ${ARGN})
    _cdpm_pkg_matches_masks("${name}" "${masks_json}" in_scope)
    if(NOT in_scope)
        return()
    endif()

    get_property(merged GLOBAL PROPERTY CDPM_MERGED_REPO)
    if(NOT merged)
        set(merged [=[{"packages":{}}]=])
    endif()
    if(NOT arg_CLAIMED)
        string(JSON existing ERROR_VARIABLE exists_err GET "${merged}" packages "${name}")
        if(NOT exists_err)
            return()
        endif()
        get_property(owners GLOBAL PROPERTY CDPM_REGISTRY_OWNERS)
        if(owners)
            string(JSON existing_owner ERROR_VARIABLE owner_err GET "${owners}" "${name}")
            if(NOT owner_err)
                return()
            endif()
        else()
            set(owners "{}")
        endif()
        _cdpm_json_set_safe("${owners}" "${name}" "loaded" STRING owners)
        set_property(GLOBAL PROPERTY CDPM_REGISTRY_OWNERS "${owners}")
    endif()

    _cdpm_validate_repo_package("${name}" "${pkg_json}")
    if(schema EQUAL 2)
        _cdpm_registry_validate_schema2_patch_assets("${name}" "${pkg_json}" "${manifest_dir}")
    endif()

    if(NOT arg_SKIP_ALIAS_CHECK)
        cdpm_get_package_find_name("${name}" "${pkg_json}" find_name)
        string(TOLOWER "${find_name}" find_key)
        string(JSON merged_count LENGTH "${merged}" packages)
        if(merged_count GREATER 0)
            math(EXPR merged_last "${merged_count} - 1")
            foreach(merged_index RANGE 0 ${merged_last})
                string(JSON other_name MEMBER "${merged}" packages ${merged_index})
                string(JSON other_meta GET "${merged}" packages "${other_name}")
                cdpm_get_package_find_name("${other_name}" "${other_meta}" other_find_name)
                string(TOLOWER "${other_find_name}" other_find_key)
                if(find_key STREQUAL other_find_key)
                    message(FATAL_ERROR "[cdpm] duplicate find_package_name '${find_name}' for packages "
                        "'${other_name}' and '${name}'.")
                endif()
            endforeach()
        endif()
    endif()

    string(JSON merged SET "${merged}" packages "${name}" "${pkg_json}")
    set_property(GLOBAL PROPERTY CDPM_MERGED_REPO "${merged}")
    _cdpm_registry_set_provenance("${name}" "${schema}" "${repo_root}" "${manifest_dir}")
endfunction()

function(_cdpm_registry_load_schema1 repo_file repo_root packages masks_json)
    set_property(GLOBAL PROPERTY CDPM_REGISTRY_ALIAS_CACHE "")
    set(seen "")
    _cdpm_json_foreach("${packages}" package_keys)
    foreach(original_name IN LISTS package_keys)
        string(TOLOWER "${original_name}" name)
        if(name IN_LIST seen)
            message(FATAL_ERROR "[cdpm] repository '${repo_file}': duplicate package '${name}' after lower-case "
                "normalization.")
        endif()
        list(APPEND seen "${name}")
        string(JSON pkg_json GET "${packages}" "${original_name}")
        _cdpm_registry_register_package("${repo_file}" "${repo_root}" 1 "${name}" "${pkg_json}"
            "${repo_root}" "${masks_json}")
    endforeach()
endfunction()

function(_cdpm_registry_load_schema2 repo_file repo_root raw masks_json)
    _cdpm_json_foreach("${raw}" root_keys)
    foreach(root_key IN LISTS root_keys)
        if(NOT root_key MATCHES [[^(repo_schema|packages)$]])
            message(FATAL_ERROR "[cdpm] schema-2 repository '${repo_file}': unexpected root member '${root_key}'.")
        endif()
    endforeach()
    string(JSON packages_type ERROR_VARIABLE packages_type_err TYPE "${raw}" packages)
    if(packages_type_err OR NOT packages_type STREQUAL "OBJECT")
        message(FATAL_ERROR "[cdpm] schema-2 repository '${repo_file}': 'packages' must be an object map.")
    endif()
    string(JSON packages GET "${raw}" packages)

    set(seen "")
    set(normalized_packages "{}")
    _cdpm_json_foreach("${packages}" package_keys)
    # Validate the complete index before opening any manifest.
    foreach(original_name IN LISTS package_keys)
        string(TOLOWER "${original_name}" name)
        if(name STREQUAL "" OR name IN_LIST seen)
            message(FATAL_ERROR "[cdpm] schema-2 repository '${repo_file}': duplicate or empty package key '${name}' "
                "after lower-case normalization.")
        endif()
        list(APPEND seen "${name}")

        string(JSON path_type TYPE "${packages}" "${original_name}")
        string(JSON manifest_path GET "${packages}" "${original_name}")
        if(NOT path_type STREQUAL "STRING" OR manifest_path STREQUAL "")
            message(FATAL_ERROR "[cdpm] schema-2 repository '${repo_file}': packages.${original_name} must be a "
                "non-empty relative manifest path string.")
        endif()
        _cdpm_json_set_safe("${normalized_packages}" "${name}" "${manifest_path}" STRING normalized_packages)
    endforeach()

    string(SHA256 registry_id "${repo_file}\n${raw}")
    get_property(registry_ids GLOBAL PROPERTY CDPM_SCHEMA2_REGISTRY_IDS)
    if(NOT registry_id IN_LIST registry_ids)
        list(APPEND registry_ids "${registry_id}")
        set_property(GLOBAL PROPERTY CDPM_SCHEMA2_REGISTRY_IDS "${registry_ids}")
        set_property(GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_FILE" "${repo_file}")
        set_property(GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_ROOT" "${repo_root}")
        set_property(GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_PACKAGES" "${normalized_packages}")
    endif()
    set_property(GLOBAL PROPERTY CDPM_REGISTRY_ALIAS_CACHE "")

    get_property(owners GLOBAL PROPERTY CDPM_REGISTRY_OWNERS)
    if(NOT owners)
        set(owners "{}")
    endif()
    get_property(merged GLOBAL PROPERTY CDPM_MERGED_REPO)
    foreach(original_name IN LISTS package_keys)
        string(TOLOWER "${original_name}" name)
        string(JSON manifest_path GET "${packages}" "${original_name}")
        _cdpm_registry_validate_relative_path("${manifest_path}"
            "schema-2 repository '${repo_file}' manifest for '${name}'")
        _cdpm_pkg_matches_masks("${name}" "${masks_json}" in_scope)
        if(NOT in_scope)
            continue()
        endif()
        if(merged)
            string(JSON existing ERROR_VARIABLE existing_err GET "${merged}" packages "${name}")
            if(NOT existing_err)
                continue()
            endif()
        endif()
        string(JSON existing_owner ERROR_VARIABLE owner_err GET "${owners}" "${name}")
        if(NOT owner_err)
            continue()
        endif()
        _cdpm_json_set_safe("${owners}" "${name}" "${registry_id}" STRING owners)
    endforeach()
    set_property(GLOBAL PROPERTY CDPM_REGISTRY_OWNERS "${owners}")
endfunction()

function(_cdpm_registry_materialize pkg_name registry_id out_meta)
    get_property(repo_file GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_FILE")
    get_property(repo_root GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_ROOT")
    get_property(packages GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_PACKAGES")
    string(JSON manifest_path GET "${packages}" "${pkg_name}")
    _cdpm_registry_resolve_contained_file("${repo_root}" "${manifest_path}"
        "schema-2 repository '${repo_file}' manifest for '${pkg_name}'" manifest_file)
    _cdpm_registry_read_regular_file("${manifest_file}"
        "schema-2 repository '${repo_file}' manifest for '${pkg_name}'" "${repo_root}" pkg_json manifest_file)
    string(JSON manifest_type ERROR_VARIABLE manifest_err TYPE "${pkg_json}")
    if(manifest_err OR NOT manifest_type STREQUAL "OBJECT")
        message(FATAL_ERROR "[cdpm] schema-2 package '${pkg_name}' manifest '${manifest_file}' is not a JSON object: "
            "${manifest_err}")
    endif()
    string(JSON declared_name ERROR_VARIABLE declared_name_err GET "${pkg_json}" name)
    if(NOT declared_name_err)
        string(JSON declared_name_type TYPE "${pkg_json}" name)
        string(TOLOWER "${declared_name}" declared_key)
        if(NOT declared_name_type STREQUAL "STRING" OR NOT declared_key STREQUAL pkg_name)
            message(FATAL_ERROR "[cdpm] schema-2 manifest '${manifest_file}': package name '${declared_name}' "
                "does not match index key '${pkg_name}'.")
        endif()
    endif()
    cmake_path(GET manifest_file PARENT_PATH manifest_dir)
    _cdpm_registry_register_package("${repo_file}" "${repo_root}" 2 "${pkg_name}" "${pkg_json}"
        "${manifest_dir}" "[]" CLAIMED SKIP_ALIAS_CHECK)
    set(${out_meta} "${pkg_json}")
    return(PROPAGATE ${out_meta})
endfunction()

function(_cdpm_registry_find_canonical pkg_name out_found out_meta)
    string(TOLOWER "${pkg_name}" name)
    get_property(merged GLOBAL PROPERTY CDPM_MERGED_REPO)
    if(merged)
        string(JSON meta ERROR_VARIABLE meta_err GET "${merged}" packages "${name}")
        if(NOT meta_err)
            set(${out_found} TRUE)
            set(${out_meta} "${meta}")
            return(PROPAGATE ${out_found} ${out_meta})
        endif()
    endif()
    get_property(owners GLOBAL PROPERTY CDPM_REGISTRY_OWNERS)
    if(owners)
        string(JSON registry_id ERROR_VARIABLE owner_err GET "${owners}" "${name}")
        if(NOT owner_err AND NOT registry_id STREQUAL "loaded")
            _cdpm_registry_materialize("${name}" "${registry_id}" meta)
            set(${out_found} TRUE)
            set(${out_meta} "${meta}")
            return(PROPAGATE ${out_found} ${out_meta})
        endif()
    endif()
    set(${out_found} FALSE)
    set(${out_meta} "{}")
    return(PROPAGATE ${out_found} ${out_meta})
endfunction()

function(_cdpm_registry_find_alias requested out_found out_key out_meta)
    string(TOLOWER "${requested}" requested_key)
    get_property(alias_cache GLOBAL PROPERTY CDPM_REGISTRY_ALIAS_CACHE)
    if(alias_cache)
        string(JSON cached_key ERROR_VARIABLE cached_err GET "${alias_cache}" "${requested_key}")
        if(NOT cached_err)
            _cdpm_registry_find_canonical("${cached_key}" found meta)
            set(${out_found} "${found}")
            set(${out_key} "${cached_key}")
            set(${out_meta} "${meta}")
            return(PROPAGATE ${out_found} ${out_key} ${out_meta})
        endif()
    else()
        set(alias_cache "{}")
    endif()
    get_property(owners GLOBAL PROPERTY CDPM_REGISTRY_OWNERS)
    if(owners)
        _cdpm_json_foreach("${owners}" package_keys)
    else()
        get_property(merged GLOBAL PROPERTY CDPM_MERGED_REPO)
        if(merged)
            string(JSON packages GET "${merged}" packages)
            _cdpm_json_foreach("${packages}" package_keys)
        endif()
    endif()
    list(SORT package_keys)
    foreach(candidate_key IN LISTS package_keys)
        _cdpm_registry_find_canonical("${candidate_key}" found candidate_meta)
        if(NOT found)
            continue()
        endif()
        cdpm_get_package_find_name("${candidate_key}" "${candidate_meta}" find_name)
        string(TOLOWER "${find_name}" find_key)
        if(find_key STREQUAL requested_key)
            _cdpm_json_set_safe("${alias_cache}" "${requested_key}" "${candidate_key}" STRING alias_cache)
            set_property(GLOBAL PROPERTY CDPM_REGISTRY_ALIAS_CACHE "${alias_cache}")
            set(${out_found} TRUE)
            set(${out_key} "${candidate_key}")
            set(${out_meta} "${candidate_meta}")
            return(PROPAGATE ${out_found} ${out_key} ${out_meta})
        endif()
    endforeach()
    set(${out_found} FALSE)
    set(${out_key} "")
    set(${out_meta} "{}")
    return(PROPAGATE ${out_found} ${out_key} ${out_meta})
endfunction()

# Schema-dispatch implementation behind the existing ``cdpm_load_repo`` API.
function(_cdpm_registry_load_repo repo_file masks_json)
    _cdpm_registry_read_regular_file("${repo_file}" "repository index" "" raw real_repo_file)
    string(JSON repo_type ERROR_VARIABLE type_err TYPE "${raw}")
    if(type_err OR NOT repo_type STREQUAL "OBJECT")
        message(FATAL_ERROR "[cdpm] repository '${repo_file}' is not a JSON object: ${type_err}")
    endif()
    string(JSON schema ERROR_VARIABLE schema_err GET "${raw}" repo_schema)
    if(schema_err)
        message(FATAL_ERROR "[cdpm] repository '${repo_file}': missing 'repo_schema'.")
    endif()
    string(JSON schema_type TYPE "${raw}" repo_schema)
    if(NOT schema_type STREQUAL "NUMBER" OR NOT schema MATCHES [[^[12]$]])
        message(FATAL_ERROR "[cdpm] repository '${repo_file}': unsupported repo_schema '${schema}' "
            "(this cdpm understands schemas 1 and 2).")
    endif()

    cmake_path(GET real_repo_file PARENT_PATH repo_root)
    if(schema EQUAL 2)
        _cdpm_registry_load_schema2("${real_repo_file}" "${repo_root}" "${raw}" "${masks_json}")
        return()
    endif()

    string(JSON packages ERROR_VARIABLE packages_err GET "${raw}" packages)
    if(packages_err)
        return()
    endif()
    _cdpm_registry_load_schema1("${real_repo_file}" "${repo_root}" "${packages}" "${masks_json}")
endfunction()

function(_cdpm_registry_reset)
    get_property(registry_ids GLOBAL PROPERTY CDPM_SCHEMA2_REGISTRY_IDS)
    foreach(registry_id IN LISTS registry_ids)
        set_property(GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_FILE" "")
        set_property(GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_ROOT" "")
        set_property(GLOBAL PROPERTY "CDPM_SCHEMA2_${registry_id}_PACKAGES" "")
    endforeach()
    set_property(GLOBAL PROPERTY CDPM_MERGED_REPO "")
    set_property(GLOBAL PROPERTY CDPM_REPO_PROVENANCE "")
    set_property(GLOBAL PROPERTY CDPM_REGISTRY_OWNERS "")
    set_property(GLOBAL PROPERTY CDPM_SCHEMA2_REGISTRY_IDS "")
    set_property(GLOBAL PROPERTY CDPM_REGISTRY_ALIAS_CACHE "")
    set_property(GLOBAL PROPERTY CDPM_REGISTRY_CONFIG_GENERATION "")
endfunction()

function(_cdpm_registry_validate_loaded_aliases)
    get_property(owners GLOBAL PROPERTY CDPM_REGISTRY_OWNERS)
    if(owners)
        _cdpm_json_foreach("${owners}" package_keys)
    else()
        set(package_keys "")
    endif()
    list(SORT package_keys)
    set(alias_owners "{}")
    foreach(package_key IN LISTS package_keys)
        _cdpm_registry_find_canonical("${package_key}" found meta)
        cdpm_get_package_find_name("${package_key}" "${meta}" alias)
        string(TOLOWER "${alias}" alias_key)
        string(JSON previous ERROR_VARIABLE previous_err GET "${alias_owners}" "${alias_key}")
        if(NOT previous_err AND NOT previous STREQUAL package_key)
            message(FATAL_ERROR "[cdpm] duplicate find_package_name '${alias}' for packages '${previous}' and "
                "'${package_key}'.")
        endif()
        _cdpm_json_set_safe("${alias_owners}" "${alias_key}" "${package_key}" STRING alias_owners)
    endforeach()
endfunction()

function(_cdpm_registry_validate_repo_fatal registry_path)
    _cdpm_registry_reset()
    _cdpm_registry_load_repo("${registry_path}" "[]")
    _cdpm_registry_validate_loaded_aliases()
endfunction()

# Validates one physical schema-1 or schema-2 registry without mutating it. ``registry_path`` may name either the
# registry directory or its ``packages.json``. Invalid registries return ``FALSE`` and subprocess diagnostics.
function(cdpm_validate_registry registry_path out_valid out_diagnostics)
    set(index_path "${registry_path}")
    if(IS_DIRECTORY "${index_path}")
        set(index_path "${index_path}/packages.json")
    endif()
    if(NOT IS_ABSOLUTE "${index_path}")
        cmake_path(ABSOLUTE_PATH index_path NORMALIZE OUTPUT_VARIABLE index_path)
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}"
            "-DCMAKE_MODULE_PATH=${__CDPM_REGISTRY_MODULE_DIR}"
            "-DCDPM_REGISTRY_VALIDATION_PATH=${index_path}"
            -P "${__CDPM_REGISTRY_MODULE_DIR}/cdpm_registry_validation_runner.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10
    )
    string(STRIP "${output}\n${error}" diagnostics)
    if(result EQUAL 0)
        set(valid TRUE)
    else()
        set(valid FALSE)
    endif()
    set(${out_valid} "${valid}")
    set(${out_diagnostics} "${diagnostics}")
    return(PROPAGATE ${out_valid} ${out_diagnostics})
endfunction()
