include(cdpm_toolchain)
include("${CDPM_TEST_HELPERS}/helpers.cmake")

set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/host-native")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}")
file(WRITE "${tmp}/target.cmake" "set(TARGET_TOOLCHAIN_INCLUDED TRUE)\n")
set(CDPM_RUNTIME_DIR "${tmp}/runtime")
set(CMAKE_TOOLCHAIN_FILE "${tmp}/target.cmake")
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_OSX_ARCHITECTURES arm64)
cdpm_prepare_toolchain(abc host_toolchain HOST)
file(READ "${host_toolchain}" content)
if(content MATCHES "target.cmake|CMAKE_SYSTEM_NAME|CMAKE_OSX_ARCHITECTURES")
    message(FATAL_ERROR "FAIL: host wrapper leaked target toolchain state:\n${content}")
endif()
message(STATUS "PASS: prepare.host_native")
