include("${CDPM_TEST_HELPERS}/helpers.cmake")

set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/host-validation")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}")
set(runner "${tmp}/runner.cmake")
file(WRITE "${runner}" "list(PREPEND CMAKE_MODULE_PATH \"${CMAKE_MODULE_PATH}\")\ninclude(cdpm_config)\n_cdpm_normalize_host_dependencies(pkg \"\${SPEC}\" host_dependencies out)\n")
foreach(case IN ITEMS components unknown bad_name empty_version missing_version bad_map)
    if(case STREQUAL components)
        set(spec [[{"perl":{"version":"1","components":["x"]}}]])
    elseif(case STREQUAL unknown)
        set(spec [[{"perl":{"version":"1","mode":"CONFIG"}}]])
    elseif(case STREQUAL bad_name)
        set(spec [[{"bad/name":{"version":"1"}}]])
    elseif(case STREQUAL empty_version)
        set(spec [[{"perl":{"version":""}}]])
    elseif(case STREQUAL missing_version)
        set(spec [[{"perl":{}}]])
    else()
        set(spec "[]")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSPEC=${spec}" -P "${runner}" RESULT_VARIABLE rc)
    if(rc EQUAL 0)
        message(FATAL_ERROR "FAIL: invalid host dependency case '${case}' was accepted")
    endif()
endforeach()
message(STATUS "PASS: host_dependencies.validation")
