include(cdpm_config)
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/system_unknown_field")
file(MAKE_DIRECTORY "${tmp}")
file(WRITE "${tmp}/packages.json" [[{"repo_schema":1,"packages":{"x":{"source":{"type":"local","url":"."},"system_dependencies":{"Foo":{"mode":"CONFIG","identity_targets":["Foo::Foo"],"extra":true}},"versions":{"1":{}}}}}]])
cdpm_load_repo("${tmp}/packages.json")
