cmake_policy(SET CMP0011 NEW)
include(cdpm_config)
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/duplicate-find")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}/packages/a" "${tmp}/packages/b")
file(WRITE "${tmp}/packages/a/package.json" [[{"find_package_name":"Same","source":{"type":"local","url":"."},"versions":{"1":{}}}]])
file(WRITE "${tmp}/packages/b/package.json" [[{"find_package_name":"same","source":{"type":"local","url":"."},"versions":{"1":{}}}]])
file(WRITE "${tmp}/packages.json" [[{"version":1,"packages":{"a":"packages/a/package.json","b":"packages/b/package.json"}}]])
cdpm_load_repo("${tmp}/packages.json")
cdpm_validate_registry("${tmp}" valid diagnostics)
if(NOT valid)
    message(FATAL_ERROR "duplicate find_package_name detected (expected failure)")
endif()
message(STATUS "UNREACHABLE: duplicate find_package_name should have been detected")
