cmake_policy(SET CMP0011 NEW)
include(cdpm_config)
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/managed-unknown")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}/packages/a")
file(WRITE "${tmp}/packages/a/package.json" [[{"source":{"type":"local","url":"."},"dependencies":{"b":{"unknown":1}},"versions":{"1":{}}}]])
file(WRITE "${tmp}/packages.json" [[{"version":1,"packages":{"a":"packages/a/package.json"}}]])
cdpm_load_repo("${tmp}/packages.json")
cdpm_find_in_repo(a found meta)
