include(cdpm_config)
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/system_unsafe_name")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}/packages/x")
file(WRITE "${tmp}/packages/x/package.json" [[{"source":{"type":"local","url":"."},"system_dependencies":{"":{"mode":"CONFIG","identity_targets":["Foo::Foo"]}},"versions":{"1":{}}}]])
file(WRITE "${tmp}/packages.json" [[{"version":1,"packages":{"x":"packages/x/package.json"}}]])
cdpm_load_repo("${tmp}/packages.json")
cdpm_find_in_repo(x found meta)
