include(cdpm_build)
include("${CDPM_TEST_HELPERS}/helpers.cmake")

set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/host-context")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}/source")
set(CDPM_STORE_DIR "${tmp}/store")
set(CDPM_RUNTIME_DIR "${tmp}/runtime")
set_property(GLOBAL PROPERTY CDPM_EFFECTIVE_CONFIG [[{"packages":{},"options":{},"user":{}}]])
set(driver "tests/unit/cdpm_build/.tmp/host-context/driver.cmake")
file(WRITE "${tmp}/driver.cmake" [=[
function(cdpm_bs_contextprobe_build ctx)
    file(MAKE_DIRECTORY "${install_dir}")
    file(WRITE "${CDPM_RUNTIME_DIR}/captured.json" "${ctx}")
endfunction()
]=])
cdpm_register_build_system(contextprobe "${driver}")
set(meta "{}")
string(JSON meta SET "${meta}" build_system [["contextprobe"]])
string(JSON meta SET "${meta}" source "{\"type\":\"local\",\"url\":\"${tmp}/source\"}")
string(JSON meta SET "${meta}" versions "{\"1\":{}}")
cdpm_build_dependency(pkg 1 hash "${meta}" PROFILE HOST HOST_PREFIXES "${tmp}/host-a" "${tmp}/host-b")
file(READ "${tmp}/runtime/captured.json" ctx)
assert_json_member("${ctx}" profile HOST "driver profile")
assert_json_member("${ctx}" host_prefixes "${tmp}/host-a;${tmp}/host-b" "host prefix list semantics")
assert_json_member("${ctx}" program_path "${tmp}/host-a/bin;${tmp}/host-b/bin" "program search list")
string(JSON toolchain GET "${ctx}" toolchain)
assert_match("${toolchain}" "-host\\.cmake$" "host wrapper selected")
string(JSON prefix_path GET "${ctx}" prefix_path)
if(prefix_path MATCHES "host-a|host-b")
    message(FATAL_ERROR "FAIL: host prefixes leaked into CMAKE_PREFIX_PATH")
endif()
message(STATUS "PASS: build.host_context")
