cmake_policy(SET CMP0011 NEW)
include(cdpm_hash)
include("${CDPM_TEST_HELPERS}/helpers.cmake")
cdpm_compute_config_hash(x 1 "{}" baseline)
cdpm_compute_config_hash(x 1 "{}" first DEPENDENCY_IDENTITIES [[{"b":{"version":"2"},"a":{"version":"1"}}]])
cdpm_compute_config_hash(x 1 "{}" reordered DEPENDENCY_IDENTITIES [[{"a":{"version":"1"},"b":{"version":"2"}}]])
cdpm_compute_config_hash(x 1 "{}" changed DEPENDENCY_IDENTITIES [[{"a":{"version":"3"},"b":{"version":"2"}}]])
assert_eq("${first}" "${reordered}" "managed identities are canonical")
assert_ne("${first}" "${changed}" "managed identity changes hash")
assert_ne("${baseline}" "${first}" "managed identities participate in hash")
message(STATUS "PASS: compute.dependency_identities")
