include(cdpm_config)
include(cdpm_hash)
include("${CDPM_TEST_HELPERS}/helpers.cmake")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_GENERATOR Ninja)
set(tmp "${CMAKE_CURRENT_LIST_DIR}/.tmp/manifest_patch")
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}/packages/demo/patches")
set(patch "${tmp}/packages/demo/patches/fix.diff")
file(WRITE "${patch}" "first")
file(WRITE "${tmp}/packages/demo/package.json" "{\"source\":{\"type\":\"git\",\"url\":\"https://example.test/demo.git\"},\"versions\":{\"1.0.0\":{\"rev\":\"0123456789abcdef0123456789abcdef01234567\",\"patches\":[\"patches/fix.diff\"]}}}")
file(WRITE "${tmp}/packages.json" "{\"version\":1,\"packages\":{\"demo\":\"packages/demo/package.json\"}}")
set_property(GLOBAL PROPERTY CDPM_MERGED_REPO "")
set_property(GLOBAL PROPERTY CDPM_REPO_PROVENANCE "")
cdpm_load_repo("${tmp}/packages.json")
cdpm_find_in_repo(demo found meta)
cdpm_compute_config_hash(demo 1.0.0 "${meta}" before)
file(WRITE "${patch}" "second")
cdpm_compute_config_hash(demo 1.0.0 "${meta}" after)
assert_ne("${before}" "${after}" "manifest-relative patch bytes participate in the hash")
file(REMOVE_RECURSE "${tmp}")
message(STATUS "PASS: version 1 manifest-relative patches feed config hash")
